/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormMain.java
 *
 * Created on Apr 25, 2011, 1:10:07 PM
 */
package ui;

import com.pagosoft.plaf.PgsBorders;
import com.pagosoft.plaf.PgsLookAndFeel;
import com.pagosoft.plaf.PlafOptions;
import com.pagosoft.plaf.ThemeFactory;
import documenttypesupport.AnyToTextConverter;
import internetsearch.BingSearch;
import internetsearch.InternetSearchManager;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Map;
import java.util.Vector;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;

import preprocess.KeyWordsRemover;
//import javax.swing.ActionMap;
//import javax.swing.InputMap;
//import javax.swing.JComponent;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
//import javax.swing.KeyStroke;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.border.BevelBorder;
import javax.swing.border.EtchedBorder;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
//import net.didion.jwnl.JWNLException;
import net.infonode.gui.laf.InfoNodeLookAndFeel;
import net.infonode.gui.laf.InfoNodeLookAndFeelTheme;
import peerdocumentsearch.IndexSearch;
import peerdocumentsearch.PeerSearchManager;
import peerdocumentsearch.TextFileIndexer;
import reportingModule.DiffMatch;
import reportingModule.DiffMatch.Diff;
import reportingModule.StringDiffer;
import reportingModule.TextHighlighter;
import uibase.ImagePanelBase;

/**
 *
 * @author Brave Heart
 */
public class FormMain extends javax.swing.JFrame {

    private Vector listData = new Vector();
    private File file1;
    private File selectFile1;
    private File selectFile2;
    final static Color HILIT_COLOR = Color.LIGHT_GRAY;
    final static Color ERROR_COLOR = Color.PINK;
    Color entryBg;
    int numberOfFiles;
    Manager manager = new Manager();
    Highlighter hilit = new DefaultHighlighter();
    Highlighter hilit2 = new DefaultHighlighter();
    String[][] temp = null;   /////////// declared as a global variable
    String destFolderPath = null;
    Highlighter.HighlightPainter painter;
    private String sourceFolderName;
    String indexFolderPath;
    ArrayList<String> indexedFiles = new ArrayList<String>();
    ArrayList<String> fileArrayList = new ArrayList<String>();
    HashMap<File, ArrayList<String>> indexedFileList = new HashMap<File, ArrayList<String>>();

    /** Creates new form FormMain */
    public FormMain() {
        try {

           // PlafOptions.setWheelTabbedPaneEnabled(true);
           //PlafOptions.setCurrentTheme(ThemeFactory.createTheme(new Color(150, 100, 230), new Color(253,230,210), Color.BLACK));
            //PlafOptions.setAsLookAndFeel();

        } catch (Exception ex) {
        }

        initComponents();
        this.setLocationByPlatform(true);
        this.mainPanel.setBackground(new Color(245,222,179));
        singleDocProgressBar.setVisible(false);
        processingLabel.setVisible(false);
        fileListComboBox.setVisible(false);
        checkButton.setVisible(false);
//        jScrollPane1.setVisible(false);
    // jTextArea1.setVisible(false);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        newcheckPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        selectDocumentLabel = new javax.swing.JLabel();
        selectedFolderTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        exploreButton = new javax.swing.JButton();
        fileListComboBox = new javax.swing.JComboBox();
        checkButton = new javax.swing.JButton();
        peerSearchButton = new javax.swing.JButton();
        singleDocProgressBar = new javax.swing.JProgressBar();
        processingLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        firstFileTextArea = new javax.swing.JTextArea();
        searchLabel = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        firstFileSlectButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        secondFileSelectButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        secondFileTextArea = new javax.swing.JTextArea();
        settingsPanel = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new ImagePanelBase("Images" + File.separator + "background.png");
        intenetSourceSettingsPanel = new javax.swing.JPanel();
        bingIdTextField = new uibase.TextFieldBase();
        applyBindIdButton = new uibase.ButtonBase();
        bingSearchIDLable = new uibase.LableBase();
        downloadFilesCheckBox = new javax.swing.JCheckBox();
        randomSelectionRatioLabel = new javax.swing.JLabel();
        randomSelectionRatioComboBox = new javax.swing.JComboBox();
        numOfSourcesLable = new uibase.LableBase();
        numOfSourcesComboBox = new javax.swing.JComboBox();
        internetSearchImageLabel = new javax.swing.JLabel();
        PeerSearchSettingPanel = new javax.swing.JPanel();
        numOfSourcesLable1 = new uibase.LableBase();
        numOfPeerSourcesComboBox = new javax.swing.JComboBox();
        peerSearchRandomRatioComboBox = new javax.swing.JComboBox();
        randomSelectionRatioLabel1 = new javax.swing.JLabel();
        peerSearchLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keywordList = new javax.swing.JList();
        keywordLabel = new javax.swing.JLabel();
        addToListButton = new javax.swing.JButton();
        removeFromListButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        keywordTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        helpPanel = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        mainTabbedPane.setFont(new java.awt.Font("Tahoma", 0, 24));

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(1068, 500));

        selectDocumentLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        selectDocumentLabel.setText("Select the Document Folder");

        browseButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        browseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Explorer.png"))); // NOI18N
        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        exploreButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        exploreButton.setText("Explore ");
        exploreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exploreButtonActionPerformed(evt);
            }
        });

        checkButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        peerSearchButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        peerSearchButton.setText("Peer Search");
        peerSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peerSearchButtonActionPerformed(evt);
            }
        });

        processingLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        processingLabel.setText("Processing......");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(fileListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265)
                        .addComponent(checkButton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(browseButton)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(selectDocumentLabel)
                                .addGap(45, 45, 45)
                                .addComponent(selectedFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(exploreButton)
                        .addGap(18, 18, 18)
                        .addComponent(peerSearchButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(processingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(singleDocProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDocumentLabel)
                    .addComponent(selectedFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseButton)
                    .addComponent(exploreButton)
                    .addComponent(peerSearchButton))
                .addGap(142, 142, 142)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkButton))
                .addGap(147, 147, 147)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(singleDocProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processingLabel))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("New Check", new javax.swing.ImageIcon(getClass().getResource("/Images/NewCheck.png")), jPanel5); // NOI18N

        jPanel6.setPreferredSize(new java.awt.Dimension(800, 800));

        firstFileTextArea.setColumns(20);
        firstFileTextArea.setFont(new java.awt.Font("Tahoma", 0, 12));
        firstFileTextArea.setLineWrap(true);
        firstFileTextArea.setRows(5);
        jScrollPane2.setViewportView(firstFileTextArea);
        firstFileTextArea.getAccessibleContext().setAccessibleParent(jScrollPane2);

        searchLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        searchLabel.setText("Search");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setText("File 1");

        firstFileSlectButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        firstFileSlectButton.setText("Select");
        firstFileSlectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstFileSlectButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setText("File 2");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        secondFileSelectButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        secondFileSelectButton.setText("Select");
        secondFileSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondFileSelectButtonActionPerformed(evt);
            }
        });

        showButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        nextButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        secondFileTextArea.setColumns(20);
        secondFileTextArea.setRows(5);
        jScrollPane3.setViewportView(secondFileTextArea);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(searchLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondFileSelectButton)
                            .addComponent(searchButton)
                            .addComponent(showButton)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(firstFileSlectButton)
                                .addGap(18, 18, 18)
                                .addComponent(nextButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(previousButton))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstFileSlectButton)
                            .addComponent(nextButton)
                            .addComponent(previousButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondFileSelectButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showButton)
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton)))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Results      ", new javax.swing.ImageIcon(getClass().getResource("/Images/results.png")), jPanel6); // NOI18N

        javax.swing.GroupLayout newcheckPanelLayout = new javax.swing.GroupLayout(newcheckPanel);
        newcheckPanel.setLayout(newcheckPanelLayout);
        newcheckPanelLayout.setHorizontalGroup(
            newcheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newcheckPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newcheckPanelLayout.setVerticalGroup(
            newcheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newcheckPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Plagiarism Check", new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png")), newcheckPanel); // NOI18N

        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane4.setFont(new java.awt.Font("Tahoma", 0, 18));

        intenetSourceSettingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Internet Source Search", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        intenetSourceSettingsPanel.setFont(new java.awt.Font("Tahoma", 0, 14));
        intenetSourceSettingsPanel.setPreferredSize(new java.awt.Dimension(800, 244));
        intenetSourceSettingsPanel.setVerifyInputWhenFocusTarget(false);

        applyBindIdButton.setText("Apply ID");

        bingSearchIDLable.setText("Bing Search ID :");

        downloadFilesCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14));
        downloadFilesCheckBox.setText("Download Files For Cross Check");

        randomSelectionRatioLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        randomSelectionRatioLabel.setText("Random Selection Ratio : ");

        randomSelectionRatioComboBox.setFont(new java.awt.Font("Tahoma", 0, 14));
        randomSelectionRatioComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.10", "0.15", "0.20", "0.25", "0.30", "0.35", "0.40", "0.45", "0.50", "0.55" }));

        numOfSourcesLable.setText("Number of Sources per Document : ");

        numOfSourcesComboBox.setFont(new java.awt.Font("Tahoma", 0, 14));
        numOfSourcesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "10", "15" }));

        internetSearchImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Internet.png"))); // NOI18N

        javax.swing.GroupLayout intenetSourceSettingsPanelLayout = new javax.swing.GroupLayout(intenetSourceSettingsPanel);
        intenetSourceSettingsPanel.setLayout(intenetSourceSettingsPanelLayout);
        intenetSourceSettingsPanelLayout.setHorizontalGroup(
            intenetSourceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intenetSourceSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intenetSourceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(intenetSourceSettingsPanelLayout.createSequentialGroup()
                        .addGroup(intenetSourceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(intenetSourceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bingSearchIDLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(randomSelectionRatioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(numOfSourcesLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(intenetSourceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(intenetSourceSettingsPanelLayout.createSequentialGroup()
                                .addGroup(intenetSourceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(numOfSourcesComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(randomSelectionRatioComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(internetSearchImageLabel))
                            .addGroup(intenetSourceSettingsPanelLayout.createSequentialGroup()
                                .addComponent(bingIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(applyBindIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(intenetSourceSettingsPanelLayout.createSequentialGroup()
                        .addComponent(downloadFilesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(674, 674, 674))))
        );
        intenetSourceSettingsPanelLayout.setVerticalGroup(
            intenetSourceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intenetSourceSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intenetSourceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bingSearchIDLable, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(intenetSourceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bingIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(applyBindIdButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(intenetSourceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(intenetSourceSettingsPanelLayout.createSequentialGroup()
                        .addGroup(intenetSourceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(randomSelectionRatioLabel)
                            .addComponent(randomSelectionRatioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(intenetSourceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numOfSourcesLable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numOfSourcesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(downloadFilesCheckBox))
                    .addComponent(internetSearchImageLabel))
                .addGap(34, 34, 34))
        );

        PeerSearchSettingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Peer Document Search Settings", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        PeerSearchSettingPanel.setPreferredSize(new java.awt.Dimension(800, 200));

        numOfSourcesLable1.setText("Number of Sources per Document : ");

        numOfPeerSourcesComboBox.setFont(new java.awt.Font("Tahoma", 0, 14));
        numOfPeerSourcesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "10", "15" }));

        peerSearchRandomRatioComboBox.setFont(new java.awt.Font("Tahoma", 0, 14));
        peerSearchRandomRatioComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.10", "0.15", "0.20", "0.25", "0.30", "0.35", "0.40", "0.45", "0.50", "0.55" }));

        randomSelectionRatioLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        randomSelectionRatioLabel1.setText("Random Selection Ratio : ");

        peerSearchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Documents.png"))); // NOI18N

        javax.swing.GroupLayout PeerSearchSettingPanelLayout = new javax.swing.GroupLayout(PeerSearchSettingPanel);
        PeerSearchSettingPanel.setLayout(PeerSearchSettingPanelLayout);
        PeerSearchSettingPanelLayout.setHorizontalGroup(
            PeerSearchSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeerSearchSettingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PeerSearchSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randomSelectionRatioLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(numOfSourcesLable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(PeerSearchSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(numOfPeerSourcesComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(peerSearchRandomRatioComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160)
                .addComponent(peerSearchLabel)
                .addGap(157, 157, 157))
        );
        PeerSearchSettingPanelLayout.setVerticalGroup(
            PeerSearchSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeerSearchSettingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PeerSearchSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomSelectionRatioLabel1)
                    .addComponent(peerSearchRandomRatioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PeerSearchSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peerSearchLabel)
                    .addGroup(PeerSearchSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numOfSourcesLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numOfPeerSourcesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intenetSourceSettingsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeerSearchSettingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(intenetSourceSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PeerSearchSettingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Configure  ", new javax.swing.ImageIcon(getClass().getResource("/Images/Configure.png")), jPanel2); // NOI18N

        jScrollPane1.setViewportView(keywordList);

        keywordLabel.setText("Key Words ");

        addToListButton.setText("Add to List");
        addToListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToListButtonActionPerformed(evt);
            }
        });

        removeFromListButton.setText("Remove Selected");
        removeFromListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromListButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(keywordLabel)
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                    .addComponent(keywordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(removeFromListButton)
                    .addComponent(addToListButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(41, 41, 41)
                        .addComponent(okButton)))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(keywordLabel)
                        .addComponent(keywordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addToListButton))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(removeFromListButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(okButton)
                            .addComponent(cancelButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane4.addTab("General", jPanel1);

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Settings    ", new javax.swing.ImageIcon(getClass().getResource("/Images/Settings.png")), settingsPanel); // NOI18N

        jTabbedPane5.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane5.setFont(new java.awt.Font("Tahoma", 0, 18));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("About", new javax.swing.ImageIcon(getClass().getResource("/Images/Home.png")), jPanel17); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Developers ", new javax.swing.ImageIcon(getClass().getResource("/Images/Developer.png")), jPanel18); // NOI18N

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE))
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Help         ", new javax.swing.ImageIcon(getClass().getResource("/Images/Help.png")), helpPanel); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        listData.removeAllElements();
        keywordList.setListData(listData);
        // TODO add your handling code here:
}//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String content = manager.vectorToSting(listData);
        listData.removeAllElements();
        keywordList.setListData(listData);
        KeyWordsRemover keyremover = new KeyWordsRemover();
        keyremover.addKeyWordsToList("src" + File.separatorChar + "preprocess" + File.separatorChar + "StopWordList", content);
        JOptionPane jop = new JOptionPane();
        jop.showMessageDialog(this, "keywords successfully added to the list");
        
        // TODO add your handling code here:
}//GEN-LAST:event_okButtonActionPerformed

    private void removeFromListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromListButtonActionPerformed
        // Get the current selection
        int selection = keywordList.getSelectedIndex();
        if (selection >= 0) {
            // Add this item to the list and refresh
            listData.removeElementAt(selection);
            keywordList.setListData(listData);
            // As a nice touch, select the next item
            if (selection >= listData.size()) {
                selection = listData.size() - 1;
            }
            keywordList.setSelectedIndex(selection);
        }
        
        
        
        // TODO add your handling code here:
}//GEN-LAST:event_removeFromListButtonActionPerformed

    private void addToListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToListButtonActionPerformed
        // Get the text field value
        String stringValue = keywordTextField.getText();
        keywordTextField.setText("");
        // Add this item to the list and refresh
        if (stringValue != null) {
            listData.addElement(stringValue);
            keywordList.setListData(listData);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_addToListButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        
        FileOperator foperator = new FileOperator();
        try{
            if (!(numberOfFiles < 0)) {
                numberOfFiles--;
                String fileName1 = temp[numberOfFiles][0];
                String fileName2 = temp[numberOfFiles][1];
                jTextField3.setText(temp[numberOfFiles][0]);
                jTextField4.setText(temp[numberOfFiles][1]);
                jTextField2.setText(temp[numberOfFiles][2]);
                String[] texts = foperator.textSetter(fileName1, fileName2);
                String field1 = texts[0];
                String field2 = texts[1];
                firstFileTextArea.setText(field1.toLowerCase());
                secondFileTextArea.setText(field2.toLowerCase());
            }
        } catch (Exception e){
            
        }
        
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        
        FileOperator foperator = new FileOperator();
        numberOfFiles++;
        try{
            String fileName1 = temp[numberOfFiles][0];
            String fileName2 = temp[numberOfFiles][1];
            jTextField3.setText(temp[numberOfFiles][0]);
            jTextField4.setText(temp[numberOfFiles][1]);
            jTextField2.setText(temp[numberOfFiles][2]);
            String[] texts = foperator.textSetter(fileName1, fileName2);
            String field1 = texts[0];
            String field2 = texts[1];
            firstFileTextArea.setText(field1.toLowerCase());
            secondFileTextArea.setText(field2.toLowerCase());
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        /*
        painter = new DefaultHighlighter.DefaultHighlightPainter(HILIT_COLOR);
        firstFileTextArea.setHighlighter(hilit);
        secondFileTextArea.setHighlighter(hilit2);
        hilit.removeAllHighlights();
        hilit2.removeAllHighlights();
        entryBg = jTextField2.getBackground();
        String content = firstFileTextArea.getText();
        String content2 = secondFileTextArea.getText();
        String queryString = jTextField2.getText().toLowerCase();
        String[] query = null;
        if (queryString.length() <= 0) {
            return;
        }
        if (queryString.contains(":")) {
            
            query = queryString.split(":");
            
        } else {
            query = new String[1];
            query[0] = queryString;
        }
        for (int i = 0; i < query.length; i++) {
            String searchQuery = query[i];
            TextHighlighter highlighterFirstFile = new TextHighlighter();
            TextHighlighter highlighterSecondFile = new TextHighlighter();
            Integer[] highlightindexedInfoFirstFile = highlighterFirstFile.highlightTexts(content, searchQuery);
            Integer[] highlightindexedInfoSecondFile = highlighterSecondFile.highlightTexts(content2, searchQuery);
            int startIndexFirst = highlightindexedInfoFirstFile[0];
            int endIndexFirst = highlightindexedInfoFirstFile[1];
            int startIndexSecond = highlightindexedInfoSecondFile[0];
            int endIndexSecond = highlightindexedInfoSecondFile[1];
            try {
                if (startIndexFirst != -1) {
                    hilit.addHighlight(startIndexFirst, endIndexFirst, painter);
                    firstFileTextArea.setCaretPosition(endIndexFirst);
                    jTextField2.setBackground(entryBg);
                }
                if (startIndexSecond != -1) {
                    hilit2.addHighlight(startIndexSecond, endIndexSecond, painter);
                    secondFileTextArea.setCaretPosition(endIndexSecond);
                    jTextField2.setBackground(entryBg);
                }
            } catch (BadLocationException e) {
                e.printStackTrace();
            }
        }*/
}//GEN-LAST:event_searchButtonActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        String fileName1 = jTextField3.getText();
        String fileName2 = jTextField4.getText();
        FileOperator setTextToTextAreas = new FileOperator();
        String[] texts = setTextToTextAreas.textSetter(fileName1, fileName2);
        String field1 = texts[0];
        String field2 = texts[1];
        firstFileTextArea.setText(field1.toLowerCase());
        secondFileTextArea.setText(field2.toLowerCase());
}//GEN-LAST:event_showButtonActionPerformed

    private void secondFileSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondFileSelectButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            selectFile2 = fc.getSelectedFile();
            this.jTextField4.setText(selectFile2.toString());
        }
}//GEN-LAST:event_secondFileSelectButtonActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField4ActionPerformed

    private void firstFileSlectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstFileSlectButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            selectFile1 = fc.getSelectedFile();
            this.jTextField3.setText(selectFile1.toString());
        }        // TODO add your handling code here:
}//GEN-LAST:event_firstFileSlectButtonActionPerformed

    private void peerSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peerSearchButtonActionPerformed

        singleDocProgressBar.setVisible(true);
        processingLabel.setVisible(true);
        singleDocProgressBar.setIndeterminate(true);
        FileOperator fileOPerator = new FileOperator(sourceFolderName);
        fileOPerator.anyToTextConverter();
        fileOPerator.TextFileIndexer();
        destFolderPath = fileOPerator.getDestinatonFolderPath();
        indexFolderPath = fileOPerator.getIndexFolderPath();
        File[] files = manager.getFilesIntheFolder(destFolderPath);
        for (int arr = 0; arr < files.length; arr++) {
            fileArrayList.add(files[arr].getAbsolutePath());
        }
        final PeerSearchWorker psworker = new PeerSearchWorker(destFolderPath,files,indexFolderPath,fileArrayList,manager) {
            // This method is invoked when the worker is finished
            // its task
            @Override
            protected void done() {
                try {
                    singleDocProgressBar.setVisible(false);
                    processingLabel.setVisible(false);
                    temp = get();
                    setTempArray(temp);
                    jTextField3.setText(temp[0][0]);
                    jTextField4.setText(temp[0][1]);
                    jTextField2.setText(temp[0][2]);
                    String fileName1 = jTextField3.getText();
                    String fileName2 = jTextField4.getText();
                   // jTabbedPane2.setSelectedIndex(5);
                    FileOperator setTextToTextAreas = new FileOperator();
                    String[] texts = setTextToTextAreas.textSetter(fileName1, fileName2);
                    String field1 = texts[0];
                    String field2 = texts[1];
                    firstFileTextArea.setText(field1.toLowerCase());
                    secondFileTextArea.setText(field2.toLowerCase());
                } catch (InterruptedException ex) {
                    Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ExecutionException ex) {
                    Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        psworker.execute();
       

}//GEN-LAST:event_peerSearchButtonActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        singleDocProgressBar.setVisible(true);
        processingLabel.setVisible(true);
        singleDocProgressBar.setIndeterminate(true);
        String fName = (String) fileListComboBox.getSelectedItem();
        File destFolder = new File(destFolderPath);
        String selectedDocumentPath = sourceFolderName + File.separator + destFolder.getName() + File.separator + (String) fileListComboBox.getSelectedItem();
        final Worker sworker = new Worker(destFolderPath, fName, indexFolderPath, selectedDocumentPath, manager) {
            // This method is invoked when the worker is finished
            // its task
            @Override
            protected void done() {
                try {
                    singleDocProgressBar.setVisible(false);
                    processingLabel.setVisible(false);
                    temp = get();
                    setTempArray(temp);
                    jTextField3.setText(temp[0][0]);
                    jTextField4.setText(temp[0][1]);
                    jTextField2.setText(temp[0][2]);
                    if (!(jTextField3.getText().equalsIgnoreCase("") || jTextField4.getText().equalsIgnoreCase(""))) {
                        String fileName1 = jTextField3.getText();
                        String fileName2 = jTextField4.getText();
                        jTabbedPane2.setSelectedIndex(1);
                        FileOperator setTextToTextAreas = new FileOperator();
                        String[] texts = setTextToTextAreas.textSetter(fileName1, fileName2);
                        String field1 = texts[0];
                        String field2 = texts[1];
                        firstFileTextArea.setText(field1.toLowerCase());
                        secondFileTextArea.setText(field2.toLowerCase());
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ExecutionException ex) {
                    Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        sworker.execute();



    }//GEN-LAST:event_checkButtonActionPerformed

    private void exploreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exploreButtonActionPerformed
        
        FileOperator fileOPerator = new FileOperator(sourceFolderName);
        fileOPerator.anyToTextConverter();
        fileOPerator.TextFileIndexer();
        destFolderPath = fileOPerator.getDestinatonFolderPath();
        indexFolderPath = fileOPerator.getIndexFolderPath();
        File[] files = manager.getFilesIntheFolder(destFolderPath);
        for (int i = 0; i < files.length; i++) {
            if (files[i].isFile()) {
                fileListComboBox.addItem(files[i].getName());
            }
        }
        fileListComboBox.setVisible(true);
        checkButton.setVisible(true);
}//GEN-LAST:event_exploreButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setApproveButtonText("Select");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file1 = fc.getSelectedFile();
            this.selectedFolderTextField.setText(file1.toString());
            System.out.println(fc.getSelectedFile().getAbsolutePath());
            sourceFolderName = fc.getSelectedFile().getAbsolutePath();
            fc.setVisible(false);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_browseButtonActionPerformed

    void message(String msg) {
        jLabel8.setText(msg);
    }

    public void setTextToTextFields(String fileName1, String fileName2) {
        if (fileName1 == null || fileName2 == null) {
            firstFileTextArea.setText("");
            secondFileTextArea.setText("");
        } else {
            File testFile1 = new File(fileName1);
            File testFile2 = new File(fileName2);
            String field1 = "";
            String field2 = "";
            try {
                FileReader fr = new FileReader(testFile1);
                FileReader fr2 = new FileReader(testFile2);

                BufferedReader br = new BufferedReader(fr);
                BufferedReader br2 = new BufferedReader(fr2);
                System.out.println("testing phase");
                try {
                    while (br.readLine() != null) {
                        field1 = field1 + br.readLine();
                    }
                    while (br2.readLine() != null) {
                        field2 = field2 + br2.readLine();
                    }
                } catch (IOException ex) {
                    Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            firstFileTextArea.setText(field1.toLowerCase());
            secondFileTextArea.setText(field2.toLowerCase());
        }
    }


    public void setTempArray(String[][] temp){
        this.temp=temp;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PeerSearchSettingPanel;
    private javax.swing.JButton addToListButton;
    private uibase.ButtonBase applyBindIdButton;
    private uibase.TextFieldBase bingIdTextField;
    private uibase.LableBase bingSearchIDLable;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JCheckBox downloadFilesCheckBox;
    private javax.swing.JButton exploreButton;
    private javax.swing.JComboBox fileListComboBox;
    private javax.swing.JButton firstFileSlectButton;
    private javax.swing.JTextArea firstFileTextArea;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JPanel intenetSourceSettingsPanel;
    private javax.swing.JLabel internetSearchImageLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel keywordLabel;
    private javax.swing.JList keywordList;
    private javax.swing.JTextField keywordTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel newcheckPanel;
    private javax.swing.JButton nextButton;
    private javax.swing.JComboBox numOfPeerSourcesComboBox;
    private javax.swing.JComboBox numOfSourcesComboBox;
    private uibase.LableBase numOfSourcesLable;
    private uibase.LableBase numOfSourcesLable1;
    private javax.swing.JButton okButton;
    private javax.swing.JButton peerSearchButton;
    private javax.swing.JLabel peerSearchLabel;
    private javax.swing.JComboBox peerSearchRandomRatioComboBox;
    private javax.swing.JButton previousButton;
    private javax.swing.JLabel processingLabel;
    private javax.swing.JComboBox randomSelectionRatioComboBox;
    private javax.swing.JLabel randomSelectionRatioLabel;
    private javax.swing.JLabel randomSelectionRatioLabel1;
    private javax.swing.JButton removeFromListButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JButton secondFileSelectButton;
    private javax.swing.JTextArea secondFileTextArea;
    private javax.swing.JLabel selectDocumentLabel;
    private javax.swing.JTextField selectedFolderTextField;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JButton showButton;
    private javax.swing.JProgressBar singleDocProgressBar;
    // End of variables declaration//GEN-END:variables
}
