/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormMain.java
 *
 * Created on Apr 25, 2011, 1:10:07 PM
 */
package ui;

import com.pagosoft.plaf.PlafOptions;
import com.pagosoft.plaf.ThemeFactory;
import documenttypesupport.AnyToTextConverter;
import internetsearch.BingSearch;
import internetsearch.InternetSearchManager;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.ActionMap;
//import javax.swing.InputMap;
//import javax.swing.JComponent;
import javax.swing.JFileChooser;
//import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
//import net.didion.jwnl.JWNLException;
import net.infonode.gui.laf.InfoNodeLookAndFeel;
import net.infonode.gui.laf.InfoNodeLookAndFeelTheme;
import peerdocumentsearch.IndexSearch;
import peerdocumentsearch.PeerSearchManager;
import peerdocumentsearch.TextFileIndexer;
import reportingModule.DiffMatch;
import reportingModule.DiffMatch.Diff;
import reportingModule.StringDiffer;

/**
 *
 * @author Brave Heart
 */
public class FormMain extends javax.swing.JFrame {

    private File file1;
    private File selectFile1;
    private File selectFile2;
    final static Color HILIT_COLOR = Color.LIGHT_GRAY;
    final static Color ERROR_COLOR = Color.PINK;
    Color entryBg;
    int numberOfFiles;
    Manager manager = new Manager();
    Highlighter hilit = new DefaultHighlighter();
    Highlighter hilit2 = new DefaultHighlighter();

    ;
    String[][] temp = null;   /////////// declared as a global variable
    String destFolderPath = null;
    Highlighter.HighlightPainter painter;
    private String sourceFolderName;
    String indexFolderPath;
    ArrayList<String> indexedFiles = new ArrayList<String>();
    ArrayList<String> fileArrayList = new ArrayList<String>();
    //ArrayList<String> indexedFilesTesting;
    HashMap<File, ArrayList<String>> indexedFileList = new HashMap<File, ArrayList<String>>();

    /** Creates new form FormMain */
    public FormMain() {
        try {
            PlafOptions.setWheelTabbedPaneEnabled(true);
            PlafOptions.setCurrentTheme(ThemeFactory.createTheme(Color.WHITE));
            PlafOptions.setAsLookAndFeel();
        } catch (Exception ex) {
        }

        initComponents();
        jComboBox1.setVisible(false);
        jButton2.setVisible(false);
//        jScrollPane1.setVisible(false);
        // jTextArea1.setVisible(false);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        overviewPanel = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        newcheckPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        profilePanel = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        mainTabbedPane.setFont(new java.awt.Font("Tahoma", 0, 24));

        jTabbedPane5.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane5.setFont(new java.awt.Font("Tahoma", 0, 18));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("About", new javax.swing.ImageIcon(getClass().getResource("/Images/Search.png")), jPanel17); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Developers ", new javax.swing.ImageIcon(getClass().getResource("/Images/Developer.png")), jPanel18); // NOI18N

        javax.swing.GroupLayout overviewPanelLayout = new javax.swing.GroupLayout(overviewPanel);
        overviewPanel.setLayout(overviewPanelLayout);
        overviewPanelLayout.setHorizontalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE))
        );
        overviewPanelLayout.setVerticalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Overview", overviewPanel);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 18));

        jLabel4.setText("Select the Document Folder");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Explorer.png"))); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Explore ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton10.setText("Peer Search");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addComponent(jButton1))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton10))))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("New Check", new javax.swing.ImageIcon(getClass().getResource("/Images/NewCheck.png")), jPanel5); // NOI18N

        jPanel6.setPreferredSize(new java.awt.Dimension(800, 800));

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel5.setText("Search");

        jLabel6.setText("file 1");

        jButton4.setText("Select");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("File 2");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton5.setText("Select");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Show");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Next");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Previous");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5)
                                    .addComponent(jButton4)
                                    .addComponent(jButton6)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButton7))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(383, 383, 383))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Results", jPanel6);

        javax.swing.GroupLayout newcheckPanelLayout = new javax.swing.GroupLayout(newcheckPanel);
        newcheckPanel.setLayout(newcheckPanelLayout);
        newcheckPanelLayout.setHorizontalGroup(
            newcheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newcheckPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE))
        );
        newcheckPanelLayout.setVerticalGroup(
            newcheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newcheckPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Plagiarism Check", new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png")), newcheckPanel); // NOI18N

        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 0, 18));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Search", new javax.swing.ImageIcon(getClass().getResource("/Images/Search.png")), jPanel10); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Enrollments", new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png")), jPanel12); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Black List", new javax.swing.ImageIcon(getClass().getResource("/Images/BlackList.png")), jPanel11); // NOI18N

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Student Profiles", new javax.swing.ImageIcon(getClass().getResource("/Images/User.png")), profilePanel); // NOI18N

        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane4.setFont(new java.awt.Font("Tahoma", 0, 18));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Internet", new javax.swing.ImageIcon(getClass().getResource("/Images/Network.png")), jPanel14); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Peer Search", new javax.swing.ImageIcon(getClass().getResource("/Images/Users.png")), jPanel15); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Database", new javax.swing.ImageIcon(getClass().getResource("/Images/Database.png")), jPanel16); // NOI18N

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Settings", new javax.swing.ImageIcon(getClass().getResource("/Images/Settings.png")), settingsPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setApproveButtonText("Select");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file1 = fc.getSelectedFile();
            this.jTextField1.setText(file1.toString());
            System.out.println(fc.getSelectedFile().getAbsolutePath());
            sourceFolderName = fc.getSelectedFile().getAbsolutePath();
            fc.setVisible(false);
            //  jTextArea1.setText(match);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String folder = sourceFolderName;
        File souceFolder = new File(folder);

        if (souceFolder.isDirectory()) {
            destFolderPath = souceFolder.getAbsolutePath() + File.separator + souceFolder.getName();
            boolean destFolderCreated = new File(destFolderPath).mkdir();
            if (destFolderCreated) {
                AnyToTextConverter tc = new AnyToTextConverter(destFolderPath);
                tc.convertFilesInFolder(folder);
            }
        }

        TextFileIndexer indexer = null;
        String doucmentFolderPath = destFolderPath;
        File documentFolder = new File(doucmentFolderPath);
        indexFolderPath = documentFolder.getAbsolutePath() + File.separator + documentFolder.getName() + "_Index";
        try {
            indexer = new TextFileIndexer(indexFolderPath);
            indexer.indexFileOrDirectory(doucmentFolderPath);
            indexer.closeIndex();
        } catch (Exception ex) {
        }

        File[] files = manager.getFilesIntheFolder(destFolderPath);

        for (int i = 0; i < files.length; i++) {
            if (files[i].isFile()) {
                jComboBox1.addItem(files[i].getName());
            }
        }

        jComboBox1.setVisible(true);
        jButton2.setVisible(true);

        //jScrollPane1.setVisible(true);
        //jTextArea1.setVisible(true);
        //jTextArea1.setText("selecting document");
        /**try {
        temp = manager.manage(destFolderPath);
        } catch (IOException ex) {
        Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JWNLException ex) {
        Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        //jTextArea1.setText(temp[0][1]+"\n"+temp[0][1]+"\n"+temp[0][2]);// TODO add your handling code here
        jTextField3.setText(temp[0][0]);
        jTextField4.setText(temp[0][1]);
        jTextField2.setText(temp[0][2]);

        String fileName1=jTextField3.getText();
        String fileName2=jTextField4.getText();


        jTabbedPane2.setSelectedIndex(5);
        setTextToTextFields(fileName1, fileName2); **/
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            selectFile2 = fc.getSelectedFile();
            this.jTextField4.setText(selectFile2.toString());
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            selectFile1 = fc.getSelectedFile();
            this.jTextField3.setText(selectFile1.toString());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String fileName1 = jTextField3.getText();
        String fileName2 = jTextField4.getText();


        File testFile1 = new File(fileName1);
        File testFile2 = new File(fileName2);
        String field1 = "";
        String field2 = "";
        try {
            FileReader fr = new FileReader(testFile1);
            FileReader fr2 = new FileReader(testFile2);

            BufferedReader br = new BufferedReader(fr);
            BufferedReader br2 = new BufferedReader(fr2);
            System.out.println("testing phase");
            try {
                while (br.readLine() != null) {
                    field1 = field1 + br.readLine();
                }
                while (br2.readLine() != null) {
                    field2 = field2 + br2.readLine();
                }

            } catch (IOException ex) {
                Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(field1);
        System.out.println(field2);
        jTextArea2.setText(field1);
        jTextArea3.setText(field2);




    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed


        /** painter = new DefaultHighlighter.DefaultHighlightPainter(HILIT_COLOR);
        jTextArea2.setHighlighter(hilit);
        jTextArea3.setHighlighter(hilit2);
        hilit.removeAllHighlights();
        hilit2.removeAllHighlights();
        entryBg = jTextField2.getBackground();     

        String string = jTextField2.getText().toLowerCase();
        String[] query=null;
        if (string.length() <= 0) {
        //message("Nothing to search");
        return;
        }

        if(string.contains(":")){

        query = string.split(":");

        }
        else{
        query=new String[1];
        query[0]=string;
        }
        String content = jTextArea2.getText();
        String content2 = jTextArea3.getText();

        for(int i=0;i<query.length;i++){

        String s=query[i];
        int index = content.indexOf(s);
        int index2 = content2.indexOf(s);

        while (index != -1) {   // match found
        try {


        if(index!=-1){
        int end = index + s.length();
        hilit.addHighlight(index, end, painter);
        jTextArea2.setCaretPosition(end);
        jTextField2.setBackground(entryBg);
        }
        System.out.println("first file index= "+index);
        index = content.indexOf(s,index+s.length());

        //message("'" + s + "' found. Press ESC to end search");
        } catch (BadLocationException e) {
        e.printStackTrace();
        }
        }

        while (index2 != -1) {  // match found
        try {

        if(index2!=-1){
        int end2 = index2 + s.length();
        hilit2.addHighlight(index2, end2, painter);
        jTextArea3.setCaretPosition(end2);
        jTextField2.setBackground(entryBg);
        }
        System.out.println("second file index= "+index2);
        index2 = content2.indexOf(s,index2+s.length());
        // message("'" + s + "' found. Press ESC to end search");
        } catch (BadLocationException e) {
        e.printStackTrace();
        }
        }
        } **/
        painter = new DefaultHighlighter.DefaultHighlightPainter(HILIT_COLOR);
        jTextArea2.setHighlighter(hilit);
        jTextArea3.setHighlighter(hilit2);
        hilit.removeAllHighlights();
        hilit2.removeAllHighlights();
        entryBg = jTextField2.getBackground();

        String string = jTextField2.getText().toLowerCase();
        String[] query = null;
        if (string.length() <= 0) {
            //message("Nothing to search");
            return;
        }

        if (string.contains(":")) {

            query = string.split(":");

        } else {
            query = new String[1];
            query[0] = string;
        }
        String content = jTextArea2.getText();
        String content2 = jTextArea3.getText();

        for (int i = 0; i < query.length; i++) {

            String preprocessed = query[i];
            String s = content;
            System.out.println("full String is " + s);
            System.out.println("processed String is " + preprocessed);

            int index = 0;
            int length = 0;
            int startIndex = 0;
            int endIndex = 0;
            int count = 0;

            ArrayList<StringDiffer> arrayDiffer = new ArrayList<StringDiffer>();
            DiffMatch test2 = new DiffMatch();


            LinkedList<Diff> a = test2.diff_main(s, preprocessed);

            for (int j = 0; j < a.size(); j++) {

                String token = "" + a.get(j);
                String processedToken = token.trim();
                System.out.println("token is " + processedToken);
                String[] splitter = processedToken.split("~");



                StringDiffer differ = new StringDiffer(splitter[0], splitter[1]);
                arrayDiffer.add(differ);

            }

            for (int j = 0; j < arrayDiffer.size(); j++) {

                String state = arrayDiffer.get(j).getState();

                System.out.println("state is " + state);
                String preprocessedString = arrayDiffer.get(j).getProcessedString();

                System.out.println("preprocessed is " + preprocessedString);


                if (state.equalsIgnoreCase("EQUAL")) {


                    if (count == 0) {
                        startIndex = s.indexOf(preprocessedString);
                    }
                    count++;

                    if (i == arrayDiffer.size() - 1) {

                        index = s.indexOf(preprocessedString);
                        endIndex = index + preprocessedString.length();

                    } else {

                        System.out.println("before start index " + preprocessedString);


                        index = s.indexOf(preprocessedString);

                    }


                }

                if (state.equalsIgnoreCase("DELETE")) {




                    if (i == arrayDiffer.size() - 1) {

                        index = s.indexOf(preprocessedString);
                        length = preprocessedString.length();
                        endIndex = index;

                    } else {
                        length = preprocessedString.length();
                        index = index + length;
                    }

                }


            }








            int index2 = content2.indexOf(preprocessed);

            //while (startIndex != -1) {   // match found
            try {

                int end = 0;
                if (startIndex != -1) {
                    end = endIndex;
                    hilit.addHighlight(startIndex, end, painter);
                    jTextArea2.setCaretPosition(end);
                    jTextField2.setBackground(entryBg);
                }
                System.out.println("first file index= " + startIndex);
                //startIndex = content.indexOf(preprocessed,end);

                //message("'" + s + "' found. Press ESC to end search");
            } catch (BadLocationException e) {
                e.printStackTrace();
            }
            //}


        }








    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed


        numberOfFiles++;
        System.out.println(numberOfFiles);
        jTextField3.setText(temp[numberOfFiles][0]);
        jTextField4.setText(temp[numberOfFiles][1]);
        jTextField2.setText(temp[numberOfFiles][2]);
        setTextToTextFields(temp[numberOfFiles][0], temp[numberOfFiles][1]);

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        numberOfFiles--;
        System.out.println(numberOfFiles);
        jTextField3.setText(temp[numberOfFiles][0]);
        jTextField4.setText(temp[numberOfFiles][1]);
        jTextField2.setText(temp[numberOfFiles][2]);
        setTextToTextFields(temp[numberOfFiles][0], temp[numberOfFiles][1]);


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed



        //this.jTextArea1.setText("Start Processing files");
        String fName = (String) jComboBox1.getSelectedItem();
        File destFolder = new File(destFolderPath);

        String selectedDocumentPath = sourceFolderName + File.separator + destFolder.getName() + File.separator + (String) jComboBox1.getSelectedItem();
        String downloadFolderPath = null;
        System.out.print(fName);
        System.out.println("Start Downloading the internet files........................");
        //jTextArea1.append("Strting");
        BingSearch bingSearch = new BingSearch("F138552F897E2CA7C264FDAC64F8EF2021ABD3AF");
        bingSearch.setMaxNumOfResults(10);
        InternetSearchManager sd = new InternetSearchManager(bingSearch);
        sd.setRandomSelectionRatio(0.2f);

        downloadFolderPath = sd.downloadSourcesForFile(destFolderPath + File.separator + fName);
        System.out.println("downloaded folder path is " + downloadFolderPath);

        System.out.println("End Downloading the internet files........................\n");
        //jTextArea1.append("End Downloading the internet files........................\n");

        System.out.println("Start Indexing files........................\n");
        //jTextArea1.append("Start Indexing files........................\n");

        IndexSearch is = new IndexSearch(indexFolderPath);
        PeerSearchManager psm = new PeerSearchManager(is);
        psm.setRandomSelectionRatio(.50f);
        HashMap<String, Integer> selectedSources = psm.getSuspiciousDocList(selectedDocumentPath);
        Iterator it = selectedSources.entrySet().iterator();
        int selectedDocuments = 0;
        while (it.hasNext() && selectedDocuments <= 10) {
            Map.Entry pair = (Map.Entry) it.next();
            String filePath = (String) pair.getKey();
            selectedDocuments++;
            if (!filePath.equalsIgnoreCase(selectedDocumentPath)) {
                indexedFiles.add(filePath);
            }

        }

        System.out.println("End Indexing files........................\n");
        // jTextArea1.append("End  Indexing files........................\n");

        System.out.println("Starting Comparing Files........................\n");
        //jTextArea1.append("Starting Comparing Files........................\n");

        try {
            temp = manager.compareFiles(selectedDocumentPath, downloadFolderPath, indexedFiles);
        } catch (IOException ex) {
            System.out.println("There are no similar files or some error has occured");
        }
        //jTextArea1.setText(temp[0][1]+"\n"+temp[0][1]+"\n"+temp[0][2]);// TODO add your handling code here
        jTextField3.setText(temp[0][0]);
        jTextField4.setText(temp[0][1]);
        jTextField2.setText(temp[0][2]);

        String fileName1 = jTextField3.getText();
        String fileName2 = jTextField4.getText();

        jTabbedPane2.setSelectedIndex(5);
        setTextToTextFields(fileName1, fileName2);



    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        // One to one check of the documents
        String folder = sourceFolderName;
        File souceFolder = new File(folder);

        if (souceFolder.isDirectory()) {
            destFolderPath = souceFolder.getAbsolutePath() + File.separator + souceFolder.getName();
            boolean destFolderCreated = new File(destFolderPath).mkdir();
            if (destFolderCreated) {
                AnyToTextConverter tc = new AnyToTextConverter(destFolderPath);
                tc.convertFilesInFolder(folder);
            }
        }

        TextFileIndexer indexer = null;
        String doucmentFolderPath = destFolderPath;
        File documentFolder = new File(doucmentFolderPath);
        indexFolderPath = documentFolder.getAbsolutePath() + File.separator + documentFolder.getName() + "_Index";
        try {
            indexer = new TextFileIndexer(indexFolderPath);
            indexer.indexFileOrDirectory(doucmentFolderPath);
            indexer.closeIndex();
        } catch (Exception ex) {
        }

        File[] files = manager.getFilesIntheFolder(destFolderPath);

        for (int arr = 0; arr < files.length; arr++) {

            fileArrayList.add(files[arr].getAbsolutePath());

        }




        String fName = (String) jComboBox1.getSelectedItem();
        File destFolder = new File(destFolderPath);

        //String selectedDocumentPath=sourceFolderName+File.separator+ destFolder.getName()+File.separator+(String)jComboBox1.getSelectedItem();
        String downloadFolderPath = null;


        System.out.println("Start Indexing files........................\n");


        IndexSearch is = new IndexSearch(indexFolderPath);
        PeerSearchManager psm = new PeerSearchManager(is);
        psm.setRandomSelectionRatio(.25f);
        System.out.println("length is " + files.length);

        for (int i = 0; i < files.length; i++) {
            ArrayList<String> indexedFilesTesting = new ArrayList<String>();
            if (files[i].isFile()) {
                System.out.println("testing Indexing files........................\n");
                HashMap<String, Integer> selectedSources = psm.getSuspiciousDocList(files[i].getAbsolutePath());
                System.out.println("testing 2 Indexing files........................\n");
                Iterator it = selectedSources.entrySet().iterator();
                int selectedDocuments = 0;
                while (it.hasNext() && selectedDocuments < 10) {
                    Map.Entry pair = (Map.Entry) it.next();
                    String filePath = (String) pair.getKey();
                    selectedDocuments++;
                    ///if(!filePath.equalsIgnoreCase(selectedDocumentPath))
                    indexedFilesTesting.add(filePath);

                }

                indexedFileList.put(files[i], indexedFilesTesting);
                System.out.println("file " + files[i].getAbsolutePath());
                for (int j = 0; j < indexedFilesTesting.size(); j++) {
                    System.out.println("indexed file " + j + " " + indexedFilesTesting.get(j));
                }
                System.out.println("");



            }
        }
        System.out.println("End Indexing files........................\n");

        System.out.println("Start Downloading the internet files........................");


        BingSearch bingSearch = new BingSearch("F138552F897E2CA7C264FDAC64F8EF2021ABD3AF");
        bingSearch.setMaxNumOfResults(10);
        InternetSearchManager sd = new InternetSearchManager(bingSearch);
        sd.setRandomSelectionRatio(0.2f);



        //downloadFolderPath = sd.downloadSourcesForFile(destFolderPath+File.separator+files[i].getAbsolutePath() );
        // = sd.downloadSourcesForFile(destFolderPath+File.separator+files[i].getAbsolutePath() );
        HashMap<String, ArrayList<String>> downloadedFileList = sd.downloadSourcesForFileFolder(fileArrayList, destFolderPath);
















        System.out.println("downloaded folder path is " + downloadFolderPath);

        System.out.println("End Downloading the internet files........................\n");


        System.out.println("Starting Comparing Files........................\n");

//**/
        try {
            temp = manager.compareAllFiles(indexedFileList, downloadedFileList);
        } catch (IOException ex) {
            System.out.println("There are no similar files or some error has occured");
        }
        //jTextArea1.setText(temp[0][1]+"\n"+temp[0][1]+"\n"+temp[0][2]);// TODO add your handling code here
        jTextField3.setText(temp[0][0]);
        jTextField4.setText(temp[0][1]);
        jTextField2.setText(temp[0][2]);

        String fileName1 = jTextField3.getText();
        String fileName2 = jTextField4.getText();

        jTabbedPane2.setSelectedIndex(5);
        setTextToTextFields(fileName1, fileName2);



    }//GEN-LAST:event_jButton10ActionPerformed

    void message(String msg) {
        jLabel8.setText(msg);
    }

    public void setTextToTextFields(String fileName1, String fileName2) {

        if (fileName1 == null || fileName2 == null) {
            jTextArea2.setText("");
            jTextArea3.setText("");
        } else {

            File testFile1 = new File(fileName1);
            File testFile2 = new File(fileName2);
            String field1 = "";
            String field2 = "";
            try {
                FileReader fr = new FileReader(testFile1);
                FileReader fr2 = new FileReader(testFile2);

                BufferedReader br = new BufferedReader(fr);
                BufferedReader br2 = new BufferedReader(fr2);
                System.out.println("testing phase");
                try {
                    while (br.readLine() != null) {
                        field1 = field1 + br.readLine();
                    }
                    while (br2.readLine() != null) {
                        field2 = field2 + br2.readLine();
                    }

                } catch (IOException ex) {
                    Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            jTextArea2.setText(field1.toLowerCase());
            jTextArea3.setText(field2.toLowerCase());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel newcheckPanel;
    private javax.swing.JPanel overviewPanel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel settingsPanel;
    // End of variables declaration//GEN-END:variables
}
