/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminInforForm.java
 *
 * Created on Aug 30, 2011, 7:26:06 PM
 */
package gui.form;

/**
 *
 * @author Kasun
 */
public class AdminInforForm extends javax.swing.JFrame {

    /** Creates new form AdminInforForm */
    public AdminInforForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DeleteDocumentPanel = new javax.swing.JPanel();
        ProjectLocationLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        googleKeyTextField = new javax.swing.JPanel();
        ProjectLocationLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DeleteDocumentPanel2 = new javax.swing.JPanel();
        singleDetectionButton = new javax.swing.JRadioButton();
        ProjectFolderLabel1 = new javax.swing.JLabel();
        peerDetectionButton = new javax.swing.JRadioButton();
        DoneButton2 = new javax.swing.JButton();
        DoneButton = new javax.swing.JButton();
        DoneButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        DeleteDocumentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Google", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        DeleteDocumentPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DeleteDocumentPanel.setName("Google"); // NOI18N

        ProjectLocationLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        ProjectLocationLabel.setText("Search Application Key");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Google.png"))); // NOI18N

        javax.swing.GroupLayout DeleteDocumentPanelLayout = new javax.swing.GroupLayout(DeleteDocumentPanel);
        DeleteDocumentPanel.setLayout(DeleteDocumentPanelLayout);
        DeleteDocumentPanelLayout.setHorizontalGroup(
            DeleteDocumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteDocumentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DeleteDocumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteDocumentPanelLayout.createSequentialGroup()
                        .addComponent(ProjectLocationLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        DeleteDocumentPanelLayout.setVerticalGroup(
            DeleteDocumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteDocumentPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DeleteDocumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectLocationLabel)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        googleKeyTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        googleKeyTextField.setName("Bing"); // NOI18N

        ProjectLocationLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        ProjectLocationLabel1.setText("Search Application Key");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bing.png"))); // NOI18N

        javax.swing.GroupLayout googleKeyTextFieldLayout = new javax.swing.GroupLayout(googleKeyTextField);
        googleKeyTextField.setLayout(googleKeyTextFieldLayout);
        googleKeyTextFieldLayout.setHorizontalGroup(
            googleKeyTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(googleKeyTextFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(googleKeyTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(googleKeyTextFieldLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(542, Short.MAX_VALUE))
                    .addGroup(googleKeyTextFieldLayout.createSequentialGroup()
                        .addComponent(ProjectLocationLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );
        googleKeyTextFieldLayout.setVerticalGroup(
            googleKeyTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, googleKeyTextFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(googleKeyTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectLocationLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        DeleteDocumentPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Option", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        DeleteDocumentPanel2.setName("Bing"); // NOI18N

        buttonGroup1.add(singleDetectionButton);
        singleDetectionButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        singleDetectionButton.setSelected(true);
        singleDetectionButton.setText("Bing");
        singleDetectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleDetectionButtonActionPerformed(evt);
            }
        });

        ProjectFolderLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        ProjectFolderLabel1.setText("Search Choice");
        ProjectFolderLabel1.setRequestFocusEnabled(false);
        ProjectFolderLabel1.setVerifyInputWhenFocusTarget(false);

        buttonGroup1.add(peerDetectionButton);
        peerDetectionButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        peerDetectionButton.setText("Google");

        DoneButton2.setFont(new java.awt.Font("Tahoma", 0, 12));
        DoneButton2.setText("Set Default");
        DoneButton2.setPreferredSize(new java.awt.Dimension(180, 40));
        DoneButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteDocumentPanel2Layout = new javax.swing.GroupLayout(DeleteDocumentPanel2);
        DeleteDocumentPanel2.setLayout(DeleteDocumentPanel2Layout);
        DeleteDocumentPanel2Layout.setHorizontalGroup(
            DeleteDocumentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteDocumentPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectFolderLabel1)
                .addGap(33, 33, 33)
                .addComponent(singleDetectionButton)
                .addGap(18, 18, 18)
                .addComponent(peerDetectionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(DoneButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        DeleteDocumentPanel2Layout.setVerticalGroup(
            DeleteDocumentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteDocumentPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DeleteDocumentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectFolderLabel1)
                    .addComponent(singleDetectionButton)
                    .addComponent(peerDetectionButton)
                    .addComponent(DoneButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DoneButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        DoneButton.setText("Done");
        DoneButton.setPreferredSize(new java.awt.Dimension(180, 40));
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });

        DoneButton1.setFont(new java.awt.Font("Tahoma", 0, 12));
        DoneButton1.setText("Cancel");
        DoneButton1.setPreferredSize(new java.awt.Dimension(180, 40));
        DoneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeleteDocumentPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteDocumentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(googleKeyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DoneButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DeleteDocumentPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(googleKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(DeleteDocumentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoneButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        DeleteDocumentPanel.getAccessibleContext().setAccessibleName("Google");
        DeleteDocumentPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void singleDetectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleDetectionButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_singleDetectionButtonActionPerformed

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        this.dispose();
}//GEN-LAST:event_DoneButtonActionPerformed

    private void DoneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoneButton1ActionPerformed

    private void DoneButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoneButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdminInforForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DeleteDocumentPanel;
    private javax.swing.JPanel DeleteDocumentPanel2;
    private javax.swing.JButton DoneButton;
    private javax.swing.JButton DoneButton1;
    private javax.swing.JButton DoneButton2;
    private javax.swing.JLabel ProjectFolderLabel1;
    private javax.swing.JLabel ProjectLocationLabel;
    private javax.swing.JLabel ProjectLocationLabel1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel googleKeyTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton peerDetectionButton;
    private javax.swing.JRadioButton singleDetectionButton;
    // End of variables declaration//GEN-END:variables
}
