/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DocumentManagerForm.java
 *
 * Created on Jun 5, 2011, 11:41:05 AM
 */
package gui.form;

/**
 *
 * @author Brave Heart
 */
public class KBManagerForm extends javax.swing.JFrame {

    public static KBManagerForm kbManagerForm;

    /** Creates new form DocumentManagerForm */
    private KBManagerForm() {
        initComponents();
    }

    public static KBManagerForm getInstance() {
        if (kbManagerForm == null) {
            kbManagerForm = new KBManagerForm();
        }
        return kbManagerForm;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KBManagerMainPanel = new javax.swing.JPanel();
        CommandPanel = new javax.swing.JPanel();
        AddDocumentButton = new javax.swing.JButton();
        RemoveSourceButton = new javax.swing.JButton();
        AddWebLinkButton = new javax.swing.JButton();
        DoneButton = new javax.swing.JButton();
        SourceTableScrollPane = new javax.swing.JScrollPane();
        KBSourcesTable = new javax.swing.JTable();
        SourceTableSeparator = new javax.swing.JSeparator();
        KBImageLabel = new javax.swing.JLabel();
        NumOfSourcesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Knowledge Base Manager");
        setResizable(false);

        KBManagerMainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Sources :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        KBManagerMainPanel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        KBManagerMainPanel.setPreferredSize(new java.awt.Dimension(600, 360));

        CommandPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Commands :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        AddDocumentButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        AddDocumentButton.setText("Add Document");
        AddDocumentButton.setPreferredSize(new java.awt.Dimension(180, 40));

        RemoveSourceButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        RemoveSourceButton.setText("Remove Source");
        RemoveSourceButton.setPreferredSize(new java.awt.Dimension(180, 40));

        AddWebLinkButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        AddWebLinkButton.setText("Add Web Link");
        AddWebLinkButton.setPreferredSize(new java.awt.Dimension(180, 40));

        DoneButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        DoneButton.setText("Done");
        DoneButton.setPreferredSize(new java.awt.Dimension(180, 40));

        javax.swing.GroupLayout CommandPanelLayout = new javax.swing.GroupLayout(CommandPanel);
        CommandPanel.setLayout(CommandPanelLayout);
        CommandPanelLayout.setHorizontalGroup(
            CommandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommandPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CommandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoveSourceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDocumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddWebLinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CommandPanelLayout.setVerticalGroup(
            CommandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommandPanelLayout.createSequentialGroup()
                .addComponent(AddDocumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddWebLinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveSourceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        KBSourcesTable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        KBSourcesTable.setFont(new java.awt.Font("Tahoma", 0, 12));
        KBSourcesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Name", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        KBSourcesTable.setColumnSelectionAllowed(true);
        KBSourcesTable.getTableHeader().setReorderingAllowed(false);
        SourceTableScrollPane.setViewportView(KBSourcesTable);
        KBSourcesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        KBSourcesTable.getColumnModel().getColumn(0).setPreferredWidth(42);
        KBSourcesTable.getColumnModel().getColumn(1).setPreferredWidth(180);
        KBSourcesTable.getColumnModel().getColumn(2).setPreferredWidth(180);

        SourceTableSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        KBImageLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout KBManagerMainPanelLayout = new javax.swing.GroupLayout(KBManagerMainPanel);
        KBManagerMainPanel.setLayout(KBManagerMainPanelLayout);
        KBManagerMainPanelLayout.setHorizontalGroup(
            KBManagerMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KBManagerMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KBManagerMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CommandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KBImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SourceTableSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SourceTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        KBManagerMainPanelLayout.setVerticalGroup(
            KBManagerMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KBManagerMainPanelLayout.createSequentialGroup()
                .addGroup(KBManagerMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KBManagerMainPanelLayout.createSequentialGroup()
                        .addComponent(KBImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CommandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SourceTableSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(SourceTableScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addContainerGap())
        );

        NumOfSourcesLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        NumOfSourcesLabel.setText("Sources added. - ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumOfSourcesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addComponent(KBManagerMainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KBManagerMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumOfSourcesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDocumentButton;
    private javax.swing.JButton AddWebLinkButton;
    private javax.swing.JPanel CommandPanel;
    private javax.swing.JButton DoneButton;
    private javax.swing.JLabel KBImageLabel;
    private javax.swing.JPanel KBManagerMainPanel;
    private javax.swing.JTable KBSourcesTable;
    private javax.swing.JLabel NumOfSourcesLabel;
    private javax.swing.JButton RemoveSourceButton;
    private javax.swing.JScrollPane SourceTableScrollPane;
    private javax.swing.JSeparator SourceTableSeparator;
    // End of variables declaration//GEN-END:variables
}
