/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DocumentManagerForm.java
 *
 * Created on Jun 5, 2011, 11:41:05 AM
 */
package gui.form;

/**
 *
 * @author Brave Heart
 */
public class KeywordManager extends javax.swing.JFrame {

    public static KeywordManager keywordManager;

    /** Creates new form DocumentManagerForm */
    private KeywordManager() {
        initComponents();
    }

    public static KeywordManager getInstance() {
        if (keywordManager == null) {
            keywordManager = new KeywordManager();
        }
        return keywordManager;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        KeywordsManagerMainPanel = new javax.swing.JPanel();
        CommandPanel = new javax.swing.JPanel();
        AddKeywordButton = new javax.swing.JButton();
        RemoveKeyWordButton = new javax.swing.JButton();
        DoneButton = new javax.swing.JButton();
        KeywordManagerImageLabel = new javax.swing.JLabel();
        KeywordTableScrollPane = new javax.swing.JScrollPane();
        KeywordsTable = new javax.swing.JTable();
        KeywordsTableSeparator = new javax.swing.JSeparator();
        NumOfKeywordsLabel = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Keywords Manager");
        setResizable(false);

        KeywordsManagerMainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add or Remove Keywords  :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        KeywordsManagerMainPanel.setFont(new java.awt.Font("Tahoma", 0, 12));
        KeywordsManagerMainPanel.setPreferredSize(new java.awt.Dimension(600, 360));

        CommandPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Commands :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        AddKeywordButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        AddKeywordButton.setText("Add Keyword");
        AddKeywordButton.setPreferredSize(new java.awt.Dimension(180, 40));

        RemoveKeyWordButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        RemoveKeyWordButton.setText("Remove Keyword");
        RemoveKeyWordButton.setPreferredSize(new java.awt.Dimension(180, 40));

        DoneButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        DoneButton.setText("Done");
        DoneButton.setPreferredSize(new java.awt.Dimension(180, 40));

        javax.swing.GroupLayout CommandPanelLayout = new javax.swing.GroupLayout(CommandPanel);
        CommandPanel.setLayout(CommandPanelLayout);
        CommandPanelLayout.setHorizontalGroup(
            CommandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommandPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CommandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddKeywordButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveKeyWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CommandPanelLayout.setVerticalGroup(
            CommandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommandPanelLayout.createSequentialGroup()
                .addComponent(AddKeywordButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveKeyWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        KeywordManagerImageLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        KeywordsTable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        KeywordsTable.setFont(new java.awt.Font("Tahoma", 0, 12));
        KeywordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Keyword"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        KeywordsTable.setColumnSelectionAllowed(true);
        KeywordsTable.getTableHeader().setReorderingAllowed(false);
        KeywordTableScrollPane.setViewportView(KeywordsTable);
        KeywordsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        KeywordsTable.getColumnModel().getColumn(0).setPreferredWidth(42);
        KeywordsTable.getColumnModel().getColumn(1).setPreferredWidth(415);

        KeywordsTableSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout KeywordsManagerMainPanelLayout = new javax.swing.GroupLayout(KeywordsManagerMainPanel);
        KeywordsManagerMainPanel.setLayout(KeywordsManagerMainPanelLayout);
        KeywordsManagerMainPanelLayout.setHorizontalGroup(
            KeywordsManagerMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeywordsManagerMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KeywordsManagerMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeywordsManagerMainPanelLayout.createSequentialGroup()
                        .addComponent(KeywordManagerImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(KeywordsManagerMainPanelLayout.createSequentialGroup()
                        .addComponent(CommandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(KeywordsTableSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KeywordTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        KeywordsManagerMainPanelLayout.setVerticalGroup(
            KeywordsManagerMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeywordsManagerMainPanelLayout.createSequentialGroup()
                .addGroup(KeywordsManagerMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KeywordsTableSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addGroup(KeywordsManagerMainPanelLayout.createSequentialGroup()
                        .addComponent(KeywordManagerImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CommandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(KeywordTableScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addContainerGap())
        );

        NumOfKeywordsLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        NumOfKeywordsLabel.setText("Keyword added. - ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumOfKeywordsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addComponent(KeywordsManagerMainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KeywordsManagerMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumOfKeywordsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddKeywordButton;
    private javax.swing.JPanel CommandPanel;
    private javax.swing.JButton DoneButton;
    private javax.swing.JLabel KeywordManagerImageLabel;
    private javax.swing.JScrollPane KeywordTableScrollPane;
    private javax.swing.JPanel KeywordsManagerMainPanel;
    private javax.swing.JTable KeywordsTable;
    private javax.swing.JSeparator KeywordsTableSeparator;
    private javax.swing.JLabel NumOfKeywordsLabel;
    private javax.swing.JButton RemoveKeyWordButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
