/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WizardForm.java
 *
 * Created on Jun 3, 2011, 11:20:28 PM
 */
package gui.form;

import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import ui.Manager;

import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import reportingModule.PeerSearchUI;
import reportingModule.ReportingModule;
import ui.FileOperator;
import ui.peerSearchReportData;


/**
 *
 * @author Brave Heart
 */
enum TabNames {

    NewProject,
    AddDocument,
    SelectDocument,
    KnowledgeBase,
    Settings,
    StartCheck;
}

public class WizardForm extends javax.swing.JFrame {

    String destFolderPath = null;
    //String sourceFolderName = "C:\\Users\\Compaq\\Desktop\\demo";// need this
    // String fName = "Homework_Assignment_4.txt"; // need this
    String sourceFolderName;
    String fName;
    String indexFolderPath;
    Manager manager = new Manager();
    ReportData repdata;
    peerSearchReportData peerRepData;
    public static WizardForm wizardForm;

     ArrayList<String> fileArrayList = new ArrayList<String>();
     String[][] temp = null;


    /** Creates new form WizardForm */
    private WizardForm() {
        initComponents();
        ViewButton.setVisible(false);
        singleDetectionButton.setSelected(true);
        OutputStream out = new OutputStream() {

            @Override
            public void write(int b) throws IOException {
                updateTextArea(String.valueOf((char) b));
            }

            @Override
            public void write(byte[] b, int off, int len) throws IOException {
                updateTextArea(new String(b, off, len));
            }

            @Override
            public void write(byte[] b) throws IOException {
                write(b, 0, b.length);
            }
        };

        System.setOut(new PrintStream(out, true));
    //System.setErr(new PrintStream(out, true));

    }

    public static WizardForm getInstance() {
        if (wizardForm == null) {
            wizardForm = new WizardForm();
        }
        return wizardForm;
    }

    private void updateTextArea(final String text) {
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                jTextArea1.append(text);

            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        WizardMainPanel = new javax.swing.JPanel();
        WizardImageLabel = new javax.swing.JLabel();
        DescriptionPanel = new javax.swing.JPanel();
        DescriptionScrollPane = new javax.swing.JScrollPane();
        DescriptionTextArea = new javax.swing.JTextArea();
        WizardSeparator = new javax.swing.JSeparator();
        WizardTabbedPane = new javax.swing.JTabbedPane();
        ProjectLocationPanel = new javax.swing.JPanel();
        ProjectNameLabel = new javax.swing.JLabel();
        ProjectLocationLabel = new javax.swing.JLabel();
        ProjectFolderLabel = new javax.swing.JLabel();
        NameLocationTopSeparator = new javax.swing.JSeparator();
        NameLocationLabel = new javax.swing.JLabel();
        ProjectNameTextField = new javax.swing.JTextField();
        ProjectLocationTextField = new javax.swing.JTextField();
        ProjectFolderTextField = new javax.swing.JTextField();
        LocationBrowseButton = new javax.swing.JButton();
        NameLocationBottomSeparator = new javax.swing.JSeparator();
        NameLocationBannerLabel = new javax.swing.JLabel();
        DeleteProjectFilesCheckBox = new javax.swing.JCheckBox();
        Step1ImageLabel = new javax.swing.JLabel();
        singleDetectionButton = new javax.swing.JRadioButton();
        peerDetectionButton = new javax.swing.JRadioButton();
        ProjectFolderLabel1 = new javax.swing.JLabel();
        AddDocumentSeparator1 = new javax.swing.JSeparator();
        AddDocumentPanel = new javax.swing.JPanel();
        DocumentManagerButton = new javax.swing.JButton();
        AddDocumentBannerLabel = new javax.swing.JLabel();
        AddDocumentLabel = new javax.swing.JLabel();
        AddDocumentSeparator = new javax.swing.JSeparator();
        Step2ImageLabel = new javax.swing.JLabel();
        AddDocumentTipScrollPane = new javax.swing.JScrollPane();
        AddDocumentTipTextArea = new javax.swing.JTextArea();
        SelectDocumentsPanel = new javax.swing.JPanel();
        AddDocumentBannerLabel1 = new javax.swing.JLabel();
        AddDocumentLabel1 = new javax.swing.JLabel();
        ProjectLocationLabel1 = new javax.swing.JLabel();
        peerSourceTextField = new javax.swing.JTextField();
        LocationBrowseButton1 = new javax.swing.JButton();
        AddDocumentSeparator2 = new javax.swing.JSeparator();
        KnowledgeBasePanel = new javax.swing.JPanel();
        KBManagerButton = new javax.swing.JButton();
        KBManagerBannerLabel = new javax.swing.JLabel();
        KBManagerButton1 = new javax.swing.JButton();
        KBManagerLabel = new javax.swing.JLabel();
        KBManagerSeparator = new javax.swing.JSeparator();
        KeywordLabel = new javax.swing.JLabel();
        KeyWordSeparator = new javax.swing.JSeparator();
        KeywordTipScrollPane = new javax.swing.JScrollPane();
        KeywordTipTextArea = new javax.swing.JTextArea();
        KBManagerScrollPane = new javax.swing.JScrollPane();
        KBManagerTextArea = new javax.swing.JTextArea();
        Step3ImageLabel = new javax.swing.JLabel();
        SettingsPanel = new javax.swing.JPanel();
        SettingsBannerLabel = new javax.swing.JLabel();
        Step4ImageLabel = new javax.swing.JLabel();
        SettingsLabel = new javax.swing.JLabel();
        SettingsSeparator = new javax.swing.JSeparator();
        PerSettingsScrollPane = new javax.swing.JScrollPane();
        PerSettingsTipTextArea = new javax.swing.JTextArea();
        NumOfPeerDocLabel = new javax.swing.JLabel();
        NumOfExternalLabel = new javax.swing.JLabel();
        NumOfExternalSourcesComboBox = new javax.swing.JComboBox();
        NumOfPeerSourceComboBox = new javax.swing.JComboBox();
        ModesOfCheckLabel = new javax.swing.JLabel();
        ModesOfCheckSeparator = new javax.swing.JSeparator();
        PharaphraseCheckBox = new javax.swing.JCheckBox();
        StartCheckPanel = new javax.swing.JPanel();
        CheckControlButton = new javax.swing.JButton();
        CheckBannerLabel = new javax.swing.JLabel();
        Step5ImageLabel = new javax.swing.JLabel();
        TaskCompletionLabel = new javax.swing.JLabel();
        TaskCompletionSeparator = new javax.swing.JSeparator();
        KnowledgeBaseCompletionLabel = new javax.swing.JLabel();
        PreprocessDocumentCompletionLabel = new javax.swing.JLabel();
        IndexFilesCompletionLabel = new javax.swing.JLabel();
        CrossCheckCompletionLabel = new javax.swing.JLabel();
        DonloadFileProgressBar = new javax.swing.JProgressBar();
        PreprocessDocumentProgressBar = new javax.swing.JProgressBar();
        CreateIndexProgressBar = new javax.swing.JProgressBar();
        CrossCheckProgressBar = new javax.swing.JProgressBar();
        CommandSeparator = new javax.swing.JSeparator();
        CommandsLabel = new javax.swing.JLabel();
        CommandTipScrollPane = new javax.swing.JScrollPane();
        CommandTipTextArea = new javax.swing.JTextArea();
        ViewButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        WizardNextButton = new javax.swing.JButton();
        WizardPreviousButton = new javax.swing.JButton();

        jLabel20.setText("jLabel20");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Project");
        setResizable(false);

        WizardMainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Plagiarism Check Wizard :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        WizardMainPanel.setPreferredSize(new java.awt.Dimension(780, 380));

        WizardImageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        WizardImageLabel.setPreferredSize(new java.awt.Dimension(300, 250));

        DescriptionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        DescriptionPanel.setPreferredSize(new java.awt.Dimension(300, 50));

        DescriptionScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        DescriptionTextArea.setColumns(20);
        DescriptionTextArea.setEditable(false);
        DescriptionTextArea.setFont(new java.awt.Font("Tahoma", 0, 12));
        DescriptionTextArea.setLineWrap(true);
        DescriptionTextArea.setRows(5);
        DescriptionTextArea.setText("This area contains helpful information for each step of plagiarism detection process.");
        DescriptionTextArea.setBorder(null);
        DescriptionScrollPane.setViewportView(DescriptionTextArea);

        javax.swing.GroupLayout DescriptionPanelLayout = new javax.swing.GroupLayout(DescriptionPanel);
        DescriptionPanel.setLayout(DescriptionPanelLayout);
        DescriptionPanelLayout.setHorizontalGroup(
            DescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DescriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        DescriptionPanelLayout.setVerticalGroup(
            DescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DescriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        WizardSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        WizardTabbedPane.setEnabled(false);
        WizardTabbedPane.setFont(new java.awt.Font("Tahoma", 0, 12));
        WizardTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                WizardTabbedPaneStateChanged(evt);
            }
        });

        ProjectLocationPanel.setBackground(new java.awt.Color(255, 255, 255));

        ProjectNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        ProjectNameLabel.setText("Project Name:");

        ProjectLocationLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        ProjectLocationLabel.setText("Project Location:");

        ProjectFolderLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        ProjectFolderLabel.setText("Project Folder:");

        NameLocationLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        NameLocationLabel.setText("Name and Location");
        NameLocationLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ProjectNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12));
        ProjectNameTextField.setText("PlagiarismCheckProject");

        ProjectLocationTextField.setEditable(false);
        ProjectLocationTextField.setFont(new java.awt.Font("Tahoma", 0, 12));

        ProjectFolderTextField.setEditable(false);
        ProjectFolderTextField.setFont(new java.awt.Font("Tahoma", 0, 12));

        LocationBrowseButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        LocationBrowseButton.setText("Browse");
        LocationBrowseButton.setPreferredSize(new java.awt.Dimension(30, 30));
        LocationBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationBrowseButtonActionPerformed(evt);
            }
        });

        NameLocationBannerLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        NameLocationBannerLabel.setText("Step 1 - Select Name and Location");
        NameLocationBannerLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NameLocationBannerLabel.setPreferredSize(new java.awt.Dimension(212, 32));

        DeleteProjectFilesCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        DeleteProjectFilesCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12));
        DeleteProjectFilesCheckBox.setText("Delete Project Related Files After Completion");

        Step1ImageLabel.setPreferredSize(new java.awt.Dimension(32, 32));

        buttonGroup1.add(singleDetectionButton);
        singleDetectionButton.setText("Single");
        singleDetectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleDetectionButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(peerDetectionButton);
        peerDetectionButton.setText("Peer");

        ProjectFolderLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        ProjectFolderLabel1.setText("Detection Choice");

        javax.swing.GroupLayout ProjectLocationPanelLayout = new javax.swing.GroupLayout(ProjectLocationPanel);
        ProjectLocationPanel.setLayout(ProjectLocationPanelLayout);
        ProjectLocationPanelLayout.setHorizontalGroup(
            ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddDocumentSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProjectLocationPanelLayout.createSequentialGroup()
                        .addComponent(NameLocationBannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(NameLocationTopSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProjectLocationPanelLayout.createSequentialGroup()
                        .addGroup(ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLocationLabel)
                            .addComponent(DeleteProjectFilesCheckBox)
                            .addGroup(ProjectLocationPanelLayout.createSequentialGroup()
                                .addGroup(ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProjectLocationLabel)
                                    .addComponent(ProjectFolderLabel)
                                    .addComponent(ProjectFolderLabel1)
                                    .addComponent(ProjectNameLabel))
                                .addGap(41, 41, 41)
                                .addGroup(ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProjectLocationPanelLayout.createSequentialGroup()
                                        .addComponent(singleDetectionButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(peerDetectionButton))
                                    .addGroup(ProjectLocationPanelLayout.createSequentialGroup()
                                        .addGroup(ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ProjectNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ProjectFolderTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ProjectLocationTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(LocationBrowseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(Step1ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProjectLocationPanelLayout.setVerticalGroup(
            ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectLocationPanelLayout.createSequentialGroup()
                .addGroup(ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProjectLocationPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(NameLocationTopSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProjectLocationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NameLocationBannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameLocationLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddDocumentSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProjectLocationPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Step1ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProjectLocationPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProjectNameLabel)
                            .addComponent(ProjectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProjectLocationLabel)
                            .addComponent(ProjectLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LocationBrowseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProjectFolderLabel)
                            .addComponent(ProjectFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ProjectFolderLabel1)
                            .addGroup(ProjectLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(singleDetectionButton)
                                .addComponent(peerDetectionButton)))
                        .addGap(18, 18, 18)
                        .addComponent(DeleteProjectFilesCheckBox)))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        WizardTabbedPane.addTab("New Project", ProjectLocationPanel);

        AddDocumentPanel.setBackground(new java.awt.Color(255, 255, 255));

        DocumentManagerButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        DocumentManagerButton.setText("Document Manager");
        DocumentManagerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DocumentManagerButton.setPreferredSize(new java.awt.Dimension(180, 40));
        DocumentManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentManagerButtonActionPerformed(evt);
            }
        });

        AddDocumentBannerLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        AddDocumentBannerLabel.setText("Step 2 - Add Document for new Plagiarism Detection Project");
        AddDocumentBannerLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        AddDocumentBannerLabel.setPreferredSize(new java.awt.Dimension(327, 32));

        AddDocumentLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        AddDocumentLabel.setText("Add Document");
        AddDocumentLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        Step2ImageLabel.setPreferredSize(new java.awt.Dimension(32, 32));

        AddDocumentTipScrollPane.setBorder(null);
        AddDocumentTipScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        AddDocumentTipScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        AddDocumentTipScrollPane.setFont(new java.awt.Font("Tahoma", 0, 12));

        AddDocumentTipTextArea.setColumns(20);
        AddDocumentTipTextArea.setEditable(false);
        AddDocumentTipTextArea.setFont(new java.awt.Font("Tahoma", 0, 12));
        AddDocumentTipTextArea.setLineWrap(true);
        AddDocumentTipTextArea.setRows(5);
        AddDocumentTipTextArea.setText("Select document for the plagiarism test using Document Manger. You can select MS Word (.docx, .doc), .pdf, .rtf, .txt files.");
        AddDocumentTipTextArea.setWrapStyleWord(true);
        AddDocumentTipScrollPane.setViewportView(AddDocumentTipTextArea);

        javax.swing.GroupLayout AddDocumentPanelLayout = new javax.swing.GroupLayout(AddDocumentPanel);
        AddDocumentPanel.setLayout(AddDocumentPanelLayout);
        AddDocumentPanelLayout.setHorizontalGroup(
            AddDocumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDocumentPanelLayout.createSequentialGroup()
                .addGroup(AddDocumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddDocumentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AddDocumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddDocumentSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddDocumentPanelLayout.createSequentialGroup()
                                .addComponent(AddDocumentBannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                                .addComponent(Step2ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AddDocumentLabel)
                            .addComponent(AddDocumentTipScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)))
                    .addGroup(AddDocumentPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(DocumentManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        AddDocumentPanelLayout.setVerticalGroup(
            AddDocumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDocumentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddDocumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Step2ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDocumentBannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddDocumentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddDocumentSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddDocumentTipScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DocumentManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        WizardTabbedPane.addTab("Select Single Document", AddDocumentPanel);

        SelectDocumentsPanel.setBackground(new java.awt.Color(255, 255, 255));

        AddDocumentBannerLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        AddDocumentBannerLabel1.setText("Step 2 - Add Documents for new Plagiarism Detection Project");
        AddDocumentBannerLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        AddDocumentBannerLabel1.setPreferredSize(new java.awt.Dimension(327, 32));

        AddDocumentLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        AddDocumentLabel1.setText("Select Sources");
        AddDocumentLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        ProjectLocationLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        ProjectLocationLabel1.setText("Source Location");

        peerSourceTextField.setEditable(false);
        peerSourceTextField.setFont(new java.awt.Font("Tahoma", 0, 12));

        LocationBrowseButton1.setFont(new java.awt.Font("Tahoma", 0, 12));
        LocationBrowseButton1.setText("Browse");
        LocationBrowseButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        LocationBrowseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationBrowseButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectDocumentsPanelLayout = new javax.swing.GroupLayout(SelectDocumentsPanel);
        SelectDocumentsPanel.setLayout(SelectDocumentsPanelLayout);
        SelectDocumentsPanelLayout.setHorizontalGroup(
            SelectDocumentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectDocumentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelectDocumentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddDocumentBannerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDocumentLabel1)
                    .addComponent(AddDocumentSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SelectDocumentsPanelLayout.createSequentialGroup()
                        .addComponent(ProjectLocationLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(peerSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(LocationBrowseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SelectDocumentsPanelLayout.setVerticalGroup(
            SelectDocumentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectDocumentsPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(AddDocumentBannerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddDocumentLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddDocumentSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SelectDocumentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectLocationLabel1)
                    .addComponent(peerSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationBrowseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(392, Short.MAX_VALUE))
        );

        WizardTabbedPane.addTab("Select Source Documents", SelectDocumentsPanel);

        KnowledgeBasePanel.setBackground(new java.awt.Color(255, 255, 255));

        KBManagerButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        KBManagerButton.setText("Knowledge Base Manager");
        KBManagerButton.setPreferredSize(new java.awt.Dimension(180, 40));
        KBManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KBManagerButtonActionPerformed(evt);
            }
        });

        KBManagerBannerLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        KBManagerBannerLabel.setText("Step 3 - Creating a Knowledge Base For the Subject");
        KBManagerBannerLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        KBManagerBannerLabel.setPreferredSize(new java.awt.Dimension(254, 32));

        KBManagerButton1.setFont(new java.awt.Font("Tahoma", 0, 12));
        KBManagerButton1.setText("Keyword Manager");
        KBManagerButton1.setPreferredSize(new java.awt.Dimension(180, 40));
        KBManagerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KBManagerButton1ActionPerformed(evt);
            }
        });

        KBManagerLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        KBManagerLabel.setText("Knowledge Base");

        KeywordLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        KeywordLabel.setText("List of Keywords");

        KeywordTipScrollPane.setBorder(null);
        KeywordTipScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        KeywordTipScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        KeywordTipScrollPane.setFont(new java.awt.Font("Tahoma", 0, 12));

        KeywordTipTextArea.setColumns(20);
        KeywordTipTextArea.setEditable(false);
        KeywordTipTextArea.setFont(new java.awt.Font("Tahoma", 0, 12));
        KeywordTipTextArea.setLineWrap(true);
        KeywordTipTextArea.setRows(5);
        KeywordTipTextArea.setText("Using Keyword Manager create a list of Keywords that are particular to the subject of plagiarism test.");
        KeywordTipTextArea.setWrapStyleWord(true);
        KeywordTipScrollPane.setViewportView(KeywordTipTextArea);

        KBManagerScrollPane.setBorder(null);
        KBManagerScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        KBManagerScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        KBManagerScrollPane.setFont(new java.awt.Font("Tahoma", 0, 12));

        KBManagerTextArea.setColumns(20);
        KBManagerTextArea.setEditable(false);
        KBManagerTextArea.setFont(new java.awt.Font("Tahoma", 0, 12));
        KBManagerTextArea.setLineWrap(true);
        KBManagerTextArea.setRows(5);
        KBManagerTextArea.setText("Using knowledge Base Manager you can add all sort of documents and web - links to create a knwoldege base for particular subject of plagiarism test.");
        KBManagerTextArea.setWrapStyleWord(true);
        KBManagerScrollPane.setViewportView(KBManagerTextArea);

        Step3ImageLabel.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout KnowledgeBasePanelLayout = new javax.swing.GroupLayout(KnowledgeBasePanel);
        KnowledgeBasePanel.setLayout(KnowledgeBasePanelLayout);
        KnowledgeBasePanelLayout.setHorizontalGroup(
            KnowledgeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KnowledgeBasePanelLayout.createSequentialGroup()
                .addGroup(KnowledgeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KnowledgeBasePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(KnowledgeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KBManagerSeparator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                            .addComponent(KeywordLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KeyWordSeparator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KnowledgeBasePanelLayout.createSequentialGroup()
                                .addComponent(KBManagerBannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                                .addComponent(Step3ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(KeywordTipScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                            .addComponent(KBManagerScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)))
                    .addGroup(KnowledgeBasePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(KBManagerLabel))
                    .addGroup(KnowledgeBasePanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(KBManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KnowledgeBasePanelLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(KBManagerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        KnowledgeBasePanelLayout.setVerticalGroup(
            KnowledgeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KnowledgeBasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KnowledgeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KBManagerBannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Step3ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KBManagerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KBManagerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KBManagerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KBManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(KeywordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KeyWordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KeywordTipScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KBManagerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        WizardTabbedPane.addTab("Knowledge Base ", KnowledgeBasePanel);

        SettingsPanel.setBackground(new java.awt.Color(255, 255, 255));

        SettingsBannerLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        SettingsBannerLabel.setText("Step 4 - Apply Custom Settings for the Project");
        SettingsBannerLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SettingsBannerLabel.setPreferredSize(new java.awt.Dimension(237, 32));

        Step4ImageLabel.setPreferredSize(new java.awt.Dimension(32, 32));

        SettingsLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        SettingsLabel.setText("Per Document Settings");

        PerSettingsScrollPane.setBorder(null);
        PerSettingsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        PerSettingsScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        PerSettingsScrollPane.setFont(new java.awt.Font("Tahoma", 0, 12));

        PerSettingsTipTextArea.setFont(new java.awt.Font("Tahoma", 0, 12));
        PerSettingsTipTextArea.setLineWrap(true);
        PerSettingsTipTextArea.setRows(5);
        PerSettingsTipTextArea.setText("Each document can be plagiarised by external sources and other peer documents. Set approximated value for number of each kind of sources.");
        PerSettingsTipTextArea.setWrapStyleWord(true);
        PerSettingsScrollPane.setViewportView(PerSettingsTipTextArea);

        NumOfPeerDocLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        NumOfPeerDocLabel.setText("Maximum Number of Peer Documents : ");

        NumOfExternalLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        NumOfExternalLabel.setText("Maximum Number of External Sources : ");

        NumOfExternalSourcesComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NumOfExternalSourcesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "15", "20" }));
        NumOfExternalSourcesComboBox.setSelectedIndex(9);

        NumOfPeerSourceComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NumOfPeerSourceComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "15", "20" }));
        NumOfPeerSourceComboBox.setSelectedIndex(9);

        ModesOfCheckLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        ModesOfCheckLabel.setText("Modes of Check");

        PharaphraseCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        PharaphraseCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12));
        PharaphraseCheckBox.setText("Paraphrased Plagiarism Detection");

        javax.swing.GroupLayout SettingsPanelLayout = new javax.swing.GroupLayout(SettingsPanel);
        SettingsPanel.setLayout(SettingsPanelLayout);
        SettingsPanelLayout.setHorizontalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PharaphraseCheckBox)
                    .addComponent(ModesOfCheckSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addComponent(SettingsSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingsPanelLayout.createSequentialGroup()
                        .addComponent(SettingsBannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                        .addComponent(Step4ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SettingsLabel)
                    .addComponent(PerSettingsScrollPane)
                    .addGroup(SettingsPanelLayout.createSequentialGroup()
                        .addComponent(NumOfPeerDocLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumOfPeerSourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SettingsPanelLayout.createSequentialGroup()
                        .addComponent(NumOfExternalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumOfExternalSourcesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ModesOfCheckLabel))
                .addContainerGap())
        );
        SettingsPanelLayout.setVerticalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SettingsBannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Step4ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettingsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PerSettingsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumOfPeerSourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumOfPeerDocLabel))
                .addGap(18, 18, 18)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumOfExternalLabel)
                    .addComponent(NumOfExternalSourcesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(ModesOfCheckLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModesOfCheckSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PharaphraseCheckBox)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        WizardTabbedPane.addTab("Settings    ", SettingsPanel);

        StartCheckPanel.setBackground(new java.awt.Color(255, 255, 255));

        CheckControlButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        CheckControlButton.setText("Start Check");
        CheckControlButton.setPreferredSize(new java.awt.Dimension(180, 40));
        CheckControlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckControlButtonActionPerformed(evt);
            }
        });

        CheckBannerLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        CheckBannerLabel.setText("Step 5 - Start Plagiarism Detection Process");
        CheckBannerLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CheckBannerLabel.setPreferredSize(new java.awt.Dimension(252, 32));

        Step5ImageLabel.setPreferredSize(new java.awt.Dimension(32, 32));

        TaskCompletionLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        TaskCompletionLabel.setText("Task Completion");

        KnowledgeBaseCompletionLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        KnowledgeBaseCompletionLabel.setText("Downloading Internet Files");

        PreprocessDocumentCompletionLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        PreprocessDocumentCompletionLabel.setText("Preprocess Documents");

        IndexFilesCompletionLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        IndexFilesCompletionLabel.setText("Creating File Indexes");

        CrossCheckCompletionLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        CrossCheckCompletionLabel.setText("Document Cross Check");

        CommandsLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        CommandsLabel.setText("Commands");

        CommandTipScrollPane.setBorder(null);
        CommandTipScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CommandTipScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        CommandTipScrollPane.setFont(new java.awt.Font("Tahoma", 0, 12));

        CommandTipTextArea.setColumns(20);
        CommandTipTextArea.setEditable(false);
        CommandTipTextArea.setFont(new java.awt.Font("Tahoma", 0, 12));
        CommandTipTextArea.setLineWrap(true);
        CommandTipTextArea.setRows(5);
        CommandTipTextArea.setText("Use command button to initaite, terminate and view check results");
        CommandTipTextArea.setWrapStyleWord(true);
        CommandTipScrollPane.setViewportView(CommandTipTextArea);

        ViewButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        ViewButton.setText("View Report");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout StartCheckPanelLayout = new javax.swing.GroupLayout(StartCheckPanel);
        StartCheckPanel.setLayout(StartCheckPanelLayout);
        StartCheckPanelLayout.setHorizontalGroup(
            StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartCheckPanelLayout.createSequentialGroup()
                .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StartCheckPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StartCheckPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StartCheckPanelLayout.createSequentialGroup()
                                .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TaskCompletionLabel)
                                    .addComponent(CheckBannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(342, 342, 342)
                                .addComponent(Step5ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StartCheckPanelLayout.createSequentialGroup()
                                .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KnowledgeBaseCompletionLabel)
                                    .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CrossCheckCompletionLabel)
                                        .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IndexFilesCompletionLabel)
                                            .addComponent(PreprocessDocumentCompletionLabel))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CommandSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DonloadFileProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CrossCheckProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                                    .addComponent(PreprocessDocumentProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CreateIndexProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartCheckPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CommandTipScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(CheckControlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(StartCheckPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CommandsLabel)
                .addContainerGap(663, Short.MAX_VALUE))
        );
        StartCheckPanelLayout.setVerticalGroup(
            StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartCheckPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StartCheckPanelLayout.createSequentialGroup()
                        .addComponent(Step5ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(StartCheckPanelLayout.createSequentialGroup()
                        .addComponent(CheckBannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TaskCompletionLabel)))
                .addGap(20, 20, 20)
                .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KnowledgeBaseCompletionLabel)
                    .addComponent(DonloadFileProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CommandSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StartCheckPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreateIndexProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IndexFilesCompletionLabel))))
                .addGap(26, 26, 26)
                .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PreprocessDocumentCompletionLabel)
                    .addComponent(PreprocessDocumentProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CrossCheckCompletionLabel)
                    .addComponent(CrossCheckProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(CommandsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StartCheckPanelLayout.createSequentialGroup()
                        .addGroup(StartCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckControlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(StartCheckPanelLayout.createSequentialGroup()
                        .addComponent(CommandTipScrollPane, 0, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        WizardTabbedPane.addTab("Start Check   ", StartCheckPanel);

        WizardNextButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        WizardNextButton.setText("Next Step");
        WizardNextButton.setPreferredSize(new java.awt.Dimension(180, 40));
        WizardNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WizardNextButtonActionPerformed(evt);
            }
        });

        WizardPreviousButton.setBackground(new java.awt.Color(255, 255, 255));
        WizardPreviousButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        WizardPreviousButton.setText("Previous Step");
        WizardPreviousButton.setPreferredSize(new java.awt.Dimension(180, 40));
        WizardPreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WizardPreviousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WizardMainPanelLayout = new javax.swing.GroupLayout(WizardMainPanel);
        WizardMainPanel.setLayout(WizardMainPanelLayout);
        WizardMainPanelLayout.setHorizontalGroup(
            WizardMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WizardMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WizardMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WizardImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(WizardSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WizardMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WizardMainPanelLayout.createSequentialGroup()
                        .addComponent(WizardPreviousButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(WizardNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(361, 361, 361))
                    .addGroup(WizardMainPanelLayout.createSequentialGroup()
                        .addComponent(WizardTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        WizardMainPanelLayout.setVerticalGroup(
            WizardMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WizardMainPanelLayout.createSequentialGroup()
                .addComponent(WizardImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
            .addComponent(WizardSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WizardMainPanelLayout.createSequentialGroup()
                .addComponent(WizardTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(WizardMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WizardPreviousButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WizardNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WizardMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WizardMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
        );

        WizardMainPanel.getAccessibleContext().setAccessibleName("Plagiarism Check :");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DocumentManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentManagerButtonActionPerformed
        DocumentManagerForm.getInstance().setVisible(true);

    // TODO add your handling code here:
    }//GEN-LAST:event_DocumentManagerButtonActionPerformed

    private void KBManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KBManagerButtonActionPerformed
        KBManagerForm.getInstance().setVisible(true);

    // TODO add your handling code here:
    }//GEN-LAST:event_KBManagerButtonActionPerformed

    private void KBManagerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KBManagerButton1ActionPerformed
        KeywordManager.getInstance().setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_KBManagerButton1ActionPerformed

    private void WizardTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_WizardTabbedPaneStateChanged
        int currentPanelIndex = WizardTabbedPane.getSelectedIndex();
        if (currentPanelIndex == TabNames.StartCheck.ordinal()) {
            WizardNextButton.setVisible(false);
            WizardPreviousButton.setVisible(true);
        } else if (currentPanelIndex == TabNames.NewProject.ordinal()) {
            WizardPreviousButton.setVisible(false);
            WizardNextButton.setVisible(true);
        } else {
            WizardNextButton.setVisible(true);
            WizardPreviousButton.setVisible(true);
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_WizardTabbedPaneStateChanged

    private void WizardPreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WizardPreviousButtonActionPerformed
        int currentTabIndex = WizardTabbedPane.getSelectedIndex();
        WizardTabbedPane.setSelectedIndex(--currentTabIndex);

        if (peerDetectionButton.isSelected() && currentTabIndex == TabNames.AddDocument.ordinal()) {
            WizardTabbedPane.setSelectedIndex(--currentTabIndex);
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_WizardPreviousButtonActionPerformed

    private void WizardNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WizardNextButtonActionPerformed
        int currentTabIndex = WizardTabbedPane.getSelectedIndex();
        
        if (singleDetectionButton.isSelected() &&
                WizardTabbedPane.getSelectedIndex() == TabNames.NewProject.ordinal()) {
            WizardTabbedPane.setEnabledAt(TabNames.AddDocument.ordinal(), true);
            WizardTabbedPane.setSelectedIndex(++currentTabIndex);
        } else if (peerDetectionButton.isSelected() &&
                WizardTabbedPane.getSelectedIndex() == TabNames.NewProject.ordinal()) {
            WizardTabbedPane.setEnabledAt(TabNames.AddDocument.ordinal(), false);
            WizardTabbedPane.setSelectedIndex(TabNames.SelectDocument.ordinal());
            currentTabIndex = TabNames.SelectDocument.ordinal();
        } else {
            WizardTabbedPane.setSelectedIndex(++currentTabIndex);
        }
    }//GEN-LAST:event_WizardNextButtonActionPerformed

    public void setup() {
        sourceFolderName = DocumentManagerForm.folderpath;
        fName = DocumentManagerForm.fileName;
        File projectFolder = new File(ProjectFolderTextField.getText());
        projectFolder.mkdir();
        FileOperator fileOPerator = new FileOperator(sourceFolderName, projectFolder.getAbsolutePath());
        fileOPerator.anyToTextConverter();
        fileOPerator.TextFileIndexer();
        destFolderPath = fileOPerator.getDestinatonFolderPath();
        indexFolderPath = fileOPerator.getIndexFolderPath();

    }


    public void peerSetup(){
        sourceFolderName = peerSourceTextField.getText();
        File projectFolder = new File(ProjectFolderTextField.getText());
        projectFolder.mkdir();
        FileOperator fileOPerator = new FileOperator(sourceFolderName, projectFolder.getAbsolutePath());
        fileOPerator.anyToTextConverter();
        fileOPerator.TextFileIndexer();
        destFolderPath = fileOPerator.getDestinatonFolderPath();
        indexFolderPath = fileOPerator.getIndexFolderPath();
    }

    private void CheckControlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckControlButtonActionPerformed
        if (singleDetectionButton.isSelected()) {
            this.setup();
            File destFolder = new File(destFolderPath);
            String selectedDocumentPath = destFolderPath + File.separatorChar + fName;
            final Worker sworker = new Worker(destFolderPath, fName, indexFolderPath, selectedDocumentPath, manager, DonloadFileProgressBar, CreateIndexProgressBar, PreprocessDocumentProgressBar, CrossCheckProgressBar, Integer.parseInt((String) NumOfExternalSourcesComboBox.getSelectedItem()), Integer.parseInt((String) NumOfPeerSourceComboBox.getSelectedItem())) {
                // This method is invoked when the worker is finished
                @Override
                protected void done() {

                    try {
                        repdata = get();

                    } catch (InterruptedException ex) {
                        Logger.getLogger(WizardForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ExecutionException ex) {
                        Logger.getLogger(WizardForm.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    setTempArray(repdata);
                    CheckControlButton.setVisible(false);
                    ViewButton.setVisible(true);
                }
            };
            sworker.execute();
        }
        if (peerDetectionButton.isSelected()) {
            this.peerSetup();
            File[] files = manager.getFilesIntheFolder(destFolderPath);
            for (int arr = 0; arr < files.length; arr++) {
                fileArrayList.add(files[arr].getAbsolutePath());
            }
            final PeerSearchWorker psworker = new PeerSearchWorker(destFolderPath,files,indexFolderPath,fileArrayList,manager,CreateIndexProgressBar) {
            // This method is invoked when the worker is finished
            // its task
            @Override
            protected void done() {

                        try {
                            peerRepData= get();
                        } catch (InterruptedException ex) {
                            Logger.getLogger(WizardForm.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (ExecutionException ex) {
                            Logger.getLogger(WizardForm.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    CheckControlButton.setVisible(false);
                    ViewButton.setVisible(true);
                    printTemp(peerRepData);
                    
            }
            };
            psworker.execute();
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_CheckControlButtonActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        if (singleDetectionButton.isSelected()) {
        //MsgBox msg=new MsgBox(this, true);
        //msg.setVisible(true);
        System.err.print("start");
        //File destFolder = new File(destFolderPath);
        String selectedDocumentPath = destFolderPath + File.separator + DocumentManagerForm.fileName;
        ReportingModule rp = new ReportingModule();
        //rp.setVisible(true);
        rp.setDocument(selectedDocumentPath);
        rp.setTemp(repdata.getFolder());
        rp.setUrl(repdata.getUrlList());
        rp.setMap(repdata.getFileUrlMap());
        rp.setData();
        System.err.print("end");
       // msg.setVisible(false);
        rp.setVisible(true);

        }


        if (peerDetectionButton.isSelected()) {


            PeerSearchUI peerUI=new PeerSearchUI();
            peerUI.setFolder(sourceFolderName);

            peerUI.setData(peerRepData.getPeerFilesReportData(),peerRepData.getInternetFilesReportData());
            
            peerUI.processResults();
            peerUI.setResultDetails();

            peerUI.setVisible(true);





        }

    // TODO add your handling code here:
    }//GEN-LAST:event_ViewButtonActionPerformed

    private void LocationBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationBrowseButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setApproveButtonText("Select");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File selectedFolder = fc.getSelectedFile();
            ProjectLocationTextField.setText(selectedFolder.getAbsolutePath());
            ProjectFolderTextField.setText(selectedFolder.getAbsolutePath() + File.separatorChar + ProjectNameTextField.getText());
            fc.setVisible(false);
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_LocationBrowseButtonActionPerformed

    private void singleDetectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleDetectionButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_singleDetectionButtonActionPerformed

    private void LocationBrowseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationBrowseButton1ActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setApproveButtonText("Select");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File selectedFolder = fc.getSelectedFile();
            peerSourceTextField.setText(selectedFolder.getAbsolutePath());
            //peerSourceTextField.setText(selectedFolder.getAbsolutePath() + File.separatorChar + ProjectNameTextField.getText());
            fc.setVisible(false);
        }
    }//GEN-LAST:event_LocationBrowseButton1ActionPerformed

    public void setTempArray(ReportData temp) {
        this.repdata = temp;
    }


    public void printTemp(peerSearchReportData temp){
        Iterator it = temp.getInternetFilesReportData().entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pair = (Map.Entry) it.next();
            String fileName = (String)pair.getKey();
            HashMap<String,String> map = (HashMap<String,String>)pair.getValue();
           
            System.err.println(fileName);
            System.err.println();
            System.err.println();
            System.err.println(map.entrySet());
            System.err.println();
            System.err.println();
        }
        
        
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddDocumentBannerLabel;
    private javax.swing.JLabel AddDocumentBannerLabel1;
    private javax.swing.JLabel AddDocumentLabel;
    private javax.swing.JLabel AddDocumentLabel1;
    private javax.swing.JPanel AddDocumentPanel;
    private javax.swing.JSeparator AddDocumentSeparator;
    private javax.swing.JSeparator AddDocumentSeparator1;
    private javax.swing.JSeparator AddDocumentSeparator2;
    private javax.swing.JScrollPane AddDocumentTipScrollPane;
    private javax.swing.JTextArea AddDocumentTipTextArea;
    private javax.swing.JLabel CheckBannerLabel;
    private javax.swing.JButton CheckControlButton;
    private javax.swing.JSeparator CommandSeparator;
    private javax.swing.JScrollPane CommandTipScrollPane;
    private javax.swing.JTextArea CommandTipTextArea;
    private javax.swing.JLabel CommandsLabel;
    private javax.swing.JProgressBar CreateIndexProgressBar;
    private javax.swing.JLabel CrossCheckCompletionLabel;
    private javax.swing.JProgressBar CrossCheckProgressBar;
    private javax.swing.JCheckBox DeleteProjectFilesCheckBox;
    private javax.swing.JPanel DescriptionPanel;
    private javax.swing.JScrollPane DescriptionScrollPane;
    private javax.swing.JTextArea DescriptionTextArea;
    private javax.swing.JButton DocumentManagerButton;
    private javax.swing.JProgressBar DonloadFileProgressBar;
    private javax.swing.JLabel IndexFilesCompletionLabel;
    private javax.swing.JLabel KBManagerBannerLabel;
    private javax.swing.JButton KBManagerButton;
    private javax.swing.JButton KBManagerButton1;
    private javax.swing.JLabel KBManagerLabel;
    private javax.swing.JScrollPane KBManagerScrollPane;
    private javax.swing.JSeparator KBManagerSeparator;
    private javax.swing.JTextArea KBManagerTextArea;
    private javax.swing.JSeparator KeyWordSeparator;
    private javax.swing.JLabel KeywordLabel;
    private javax.swing.JScrollPane KeywordTipScrollPane;
    private javax.swing.JTextArea KeywordTipTextArea;
    private javax.swing.JLabel KnowledgeBaseCompletionLabel;
    private javax.swing.JPanel KnowledgeBasePanel;
    private javax.swing.JButton LocationBrowseButton;
    private javax.swing.JButton LocationBrowseButton1;
    private javax.swing.JLabel ModesOfCheckLabel;
    private javax.swing.JSeparator ModesOfCheckSeparator;
    private javax.swing.JLabel NameLocationBannerLabel;
    private javax.swing.JSeparator NameLocationBottomSeparator;
    private javax.swing.JLabel NameLocationLabel;
    private javax.swing.JSeparator NameLocationTopSeparator;
    private javax.swing.JLabel NumOfExternalLabel;
    private javax.swing.JComboBox NumOfExternalSourcesComboBox;
    private javax.swing.JLabel NumOfPeerDocLabel;
    private javax.swing.JComboBox NumOfPeerSourceComboBox;
    private javax.swing.JScrollPane PerSettingsScrollPane;
    private javax.swing.JTextArea PerSettingsTipTextArea;
    private javax.swing.JCheckBox PharaphraseCheckBox;
    private javax.swing.JLabel PreprocessDocumentCompletionLabel;
    private javax.swing.JProgressBar PreprocessDocumentProgressBar;
    private javax.swing.JLabel ProjectFolderLabel;
    private javax.swing.JLabel ProjectFolderLabel1;
    private javax.swing.JTextField ProjectFolderTextField;
    private javax.swing.JLabel ProjectLocationLabel;
    private javax.swing.JLabel ProjectLocationLabel1;
    private javax.swing.JPanel ProjectLocationPanel;
    private javax.swing.JTextField ProjectLocationTextField;
    private javax.swing.JLabel ProjectNameLabel;
    private javax.swing.JTextField ProjectNameTextField;
    private javax.swing.JPanel SelectDocumentsPanel;
    private javax.swing.JLabel SettingsBannerLabel;
    private javax.swing.JLabel SettingsLabel;
    private javax.swing.JPanel SettingsPanel;
    private javax.swing.JSeparator SettingsSeparator;
    private javax.swing.JPanel StartCheckPanel;
    private javax.swing.JLabel Step1ImageLabel;
    private javax.swing.JLabel Step2ImageLabel;
    private javax.swing.JLabel Step3ImageLabel;
    private javax.swing.JLabel Step4ImageLabel;
    private javax.swing.JLabel Step5ImageLabel;
    private javax.swing.JLabel TaskCompletionLabel;
    private javax.swing.JSeparator TaskCompletionSeparator;
    private javax.swing.JButton ViewButton;
    private javax.swing.JLabel WizardImageLabel;
    private javax.swing.JPanel WizardMainPanel;
    private javax.swing.JButton WizardNextButton;
    private javax.swing.JButton WizardPreviousButton;
    private javax.swing.JSeparator WizardSeparator;
    private javax.swing.JTabbedPane WizardTabbedPane;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton peerDetectionButton;
    private javax.swing.JTextField peerSourceTextField;
    private javax.swing.JRadioButton singleDetectionButton;
    // End of variables declaration//GEN-END:variables
}
